// 2026/9 宜蘭礁溪慢遊 — data.js (SSOT)
// Edit this file to update the site. Re-run `npm test` from repo root.

const TRIP = {
  title: "2026/9 宜蘭礁溪慢遊",
  emoji: "♨️",
  subtitle: "三天兩夜・四人・自駕＋客運會合・品文旅礁溪連住兩晚（含早餐）",
  heroTitle: "礁溪泡湯 × 輕健行 × 宜蘭掃街 ♨️ 三天兩夜",
  heroDesc: "9/18 上午三人開車走國５下礁溪，下午猴洞坑瀑布＋龍潭湖兩段輕鬆步道暖身，入住品文旅連泡兩晚溫泉；第四人傍晚 18:00 從文化大學搭客運南下，晚上在礁溪會合。9/19 四人一起走頭城海線看龜山島、晚上攻羅東夜市。9/20 礁溪慢活一天，傍晚吃飽再開車北返。",
  dates: { start: "2026-09-18", end: "2026-09-20" },
  people: 4,
  country: "TW",
  origin: "台北",
  destinations: ["宜蘭"],
  hotel: {
    name: "品文旅礁溪 Hotel PIN Jiaoxi",
    area: "礁溪溫泉飯店街（礁溪公園旁）",
    address: "宜蘭縣礁溪鄉健康二街 21 巷 2 號",
    note: "🔒 **已訂：9/18–9/20 連住兩晚、4 人房型、含早餐**。雲朗觀光旗下品牌，178 間客房**全部都有溫泉浴池**（碳酸氫鈉泉／美人湯）。入住 15:00 後、退房 11:00 前，**住宿附免費停車位**（戶外停車場、車位多）。除了已含的早餐 buffet（06:30–11:00），**下午茶迎賓點心（豆花、紅酒無限）與 18:00 起的免費宵夜（現煮義大利麵、關東煮、甜點）也都不用錢** — 排行程時記得留空檔回飯店吃。館內另有溫泉 SPA 水療、悅讀屋（漫畫小說＋免費咖啡）、玩起來遊戲室。",
    walking: [
      { to: "礁溪公園（就在隔壁）", minutes: 3 },
      { to: "湯圍溝溫泉公園（免費足湯）", minutes: 8 },
      { to: "礁溪火車站", minutes: 10 },
      { to: "柯氏蔥油餅／吳記花生捲", minutes: 10 },
    ],
  },
  flights: [],
  budget: null,
  extraCards: [
    {
      icon: "👥",
      title: "四人・9/18 分頭出發與會合",
      rows: [
        { key: "A 組（3 人）", val: "9/18 上午 09:00 開車從台北出發，走國５下礁溪，白天照常跑猴洞坑＋龍潭湖，15:30 入住品文旅" },
        { key: "B 組（1 人）", val: "9/18 **18:00 從文化大學出發**，搭大眾運輸南下（詳細路線見「交通」分頁）" },
        { key: "會合", val: "預計 **20:30–21:30 在礁溪轉運站會合**（A 組開車去接，離飯店約 5 分鐘）", wrap: true },
        { key: "會合後", val: "一起去湯圍溝泡免費足湯，回飯店吃免費宵夜（18:00 起供應，B 組晚餐可以留到這時候解決）", wrap: true },
        { key: "9/19–9/20", val: "四人同行，回程一起開車回台北" },
        { key: "⚠️ 注意", val: "週五傍晚國５南下是壅塞尖峰，客運可能比平常多花 30–40 分鐘，接人時間抓寬鬆一點、保持聯絡", wrap: true },
      ],
    },
    {
      icon: "🥾",
      title: "9/18 輕健行安排（不累版）",
      rows: [
        { key: "主步道", val: "猴洞坑瀑布（白石腳步道）— 入口到瀑布頂約 10–15 分鐘、約 200 階，來回含停留 45–60 分" },
        { key: "搭配", val: "龍潭湖環湖步道 — 全程平坦零陡坡，繞湖一圈約 40–50 分" },
        { key: "總量", val: "兩段加起來約 2 小時，中間開車移動 15 分，走完剛好回飯店泡湯" },
        { key: "為什麼這樣排", val: "猴洞坑短而有成就感（頂上看蘭陽平原＋龜山島），龍潭湖完全平路收尾，不會鐵腿", wrap: true },
        { key: "⚠️ 不要去", val: "林美石磐步道 2026/9/14–9/24 因施工全線封閉，正好卡到這趟；五峰旗瀑布步道狀況不明，要去請先打電話確認", wrap: true },
        { key: "備案", val: "若當天下大雨 → 改龍潭湖繞湖（撐傘可走）或直接跳過，去蘭陽博物館／潭酵天地", wrap: true },
      ],
    },
    {
      icon: "♨️",
      title: "品文旅免費餐飲時間表（別錯過）",
      rows: [
        { key: "早餐 buffet", val: "06:30–11:00（已含在房價）" },
        { key: "下午茶迎賓點心", val: "下午時段・豆花與紅酒無限供應" },
        { key: "免費宵夜", val: "18:00 起・現煮義大利麵、關東煮、甜點、蔬菜、餅乾" },
        { key: "溫泉", val: "房內溫泉浴池 24 小時 ＋ 館內溫泉 SPA 水療設施" },
        { key: "殺時間", val: "悅讀屋（二館二樓）漫畫小說＋免費咖啡、玩起來遊戲室（Switch／PS4／投籃機，現場登記）", wrap: true },
      ],
    },
    {
      icon: "✅",
      title: "9/20 回程：高乘載管制不影響我們",
      rows: [
        { key: "管制", val: "國道５號每週日 15:00–20:00 北上高乘載管制（頭城／宜蘭／羅東／蘇澳北上入口）" },
        { key: "門檻", val: "小客車須載滿 3 人（含駕駛）以上" },
        { key: "我們的狀況", val: "**四人同車 → 符合門檻，整天都可以上國５**，回程時間自由", wrap: true },
        { key: "但還是會塞", val: "管制歸管制，週日北上 10:00–20:00 本來就容易塞，16:00–19:00 最嚴重。本趟排成**傍晚吃飽再走**，19:45 左右上匝道，避開最痛的一段", wrap: true },
        { key: "若提早想走", val: "想早點回家也可以，只是 16:00–19:00 出發大概要多花 30–60 分鐘塞在雪隧前", wrap: true },
      ],
    },
  ],
};

const DAYS = [
  {
    day: 1,
    date: "2026-09-18",
    dow: "五",
    city: "宜蘭・礁溪",
    theme: "抵達・猴洞坑輕健行・晚上四人會合",
    summary: "**A 組 3 人**上午從台北走國５下礁溪（約 50 分），先吃柯氏蔥油餅＋吳記花生捲當開胃，中午三民大飯店。下午**兩段輕鬆步道**：猴洞坑瀑布（短階梯、頂上看龜山島）接龍潭湖環湖（全平路），加起來約 2 小時不會累。15:30 入住品文旅，免費下午茶＋泡房內溫泉，18:30 先吃晚餐。**B 組 1 人 18:00 從文化大學出發搭客運南下**，20:30–21:30 到礁溪轉運站會合，四人一起泡湯圍溝足湯、回飯店吃免費宵夜。",
    level: "💰💰",
    timeline: [
      { time: "09:00", event: "🚗 **A 組 3 人** 台北出發，國道１／３ → 南港系統 → 國道５（週五上午順暢，避開傍晚南下車潮）" },
      { time: "10:00", event: "🛣️ 礁溪交流道下，先找車位（礁溪路四段一帶）" },
      { time: "10:15", event: "🥐 開胃小吃：柯氏蔥油餅（蔥油餅祖師娘，現點現做）＋ 吳記花生捲冰淇淋", refs: ["keshi-scallion-pancake", "wuji-peanut-roll"] },
      { time: "11:30", event: "🍜 午餐：三民大飯店（礁溪熱炒老店，桶仔雞／三星蔥蛋）— 中午容易客滿，建議先打電話", refs: ["sanmin-restaurant"] },
      { time: "13:00", event: "🥾 **猴洞坑瀑布**（導航白石腳路196號，沿巷道白線停車）— 10–15 分登頂約 200 階，瀑布頂俯瞰蘭陽平原＋遠眺龜山島，來回含停留約 1 小時", refs: ["猴洞坑瀑布"] },
      { time: "14:30", event: "🌳 **龍潭湖環湖步道**（車程 15 分，免費停車場）— 全程平坦繞湖一圈約 40–50 分，草地與大碗公溜滑梯", refs: ["龍潭湖風景區"] },
      { time: "15:30", event: "🏨 入住品文旅礁溪（健康二街21巷2號，15:00 後 check in，免費停車）" },
      { time: "16:30", event: "🧋 飯店**免費下午茶**：豆花＋紅酒無限供應，接著泡房內溫泉池洗掉走路的疲勞" },
      { time: "18:00", event: "🚌 **B 組 1 人** 從文化大學出發：搭紅5／小15 下山到劍潭捷運站（約 25–40 分，仰德大道傍晚會塞）" },
      { time: "18:30", event: "🍲 **A 組**晚餐：太一脆皮五花肉（中山路二段56號）— 瑄瑄&G先生說「頂天的脆皮五花肉」", refs: ["taiyi-crispy-pork"] },
      { time: "18:45", event: "🚇 **B 組** 劍潭站搭淡水信義線到台北車站（3 站約 8 分），走到台北轉運站（約 5–10 分）" },
      { time: "19:15", event: "🚌 **B 組** 台北轉運站搭**葛瑪蘭客運 1915**（往羅東，經礁溪轉運站），全票 NT$112，班次密集" },
      { time: "19:45", event: "♨️ **A 組**散步到湯圍溝溫泉公園（飯店走路 8 分）先泡免費足湯、看礁溪幾米兔", refs: ["湯圍溝溫泉公園"] },
      { time: "20:30", event: "🚗 **A 組**開車到**礁溪轉運站接人**（離飯店約 5 分鐘）— 週五傍晚國５南下會塞，實際到站時間抓 20:30–21:30，保持聯絡" },
      { time: "21:00", event: "🧋 四人會合！順買礁溪香腸伯 or 蘭陽肉捲當消夜小食", refs: ["jiaoxi-sausage-bo", "lanyang-meat-roll"] },
      { time: "21:30", event: "🍝 回飯店吃**免費宵夜**（現煮義大利麵、關東煮、甜點）— **B 組的晚餐正好在這裡解決**＋悅讀屋看漫畫喝免費咖啡" },
      { time: "23:00", event: "♨️ 睡前泡房內溫泉（B 組剛坐完車，泡一下最舒服）" },
    ],
    meals: [
      { type: "開胃小吃", title: "柯氏蔥油餅 ＋ 吳記花生捲冰淇淋", note: "兩家都在礁溪路上、步行可達。柯氏是台灣Cheers 專題報導的「蔥油餅祖師娘」，DUDU FAMILY 在地人篇也推；加蛋最對味。吳記現刨花生糖＋冰淇淋＋香菜捲春餅皮，怕香菜可以說不加。", refs: ["keshi-scallion-pancake", "wuji-peanut-roll"] },
      { type: "午餐", title: "三民大飯店（礁溪熱炒老店）", note: "CHILL先生一家人跑好幾次宜蘭都沒排到的店。名字叫大飯店其實是熱炒。替代：福哥石窯雞（外酥內嫩，一天賣數百隻）或賴家手工雙醬麵。", refs: ["sanmin-restaurant", "fuge-stone-kiln-chicken", "laijia-noodle"] },
      { type: "晚餐", title: "太一脆皮五花肉", note: "瑄瑄&G先生私藏 5 間之一，主打脆皮五花。想吃日式的話換和壽司；想吃高級一點換三寸舌尖。", refs: ["taiyi-crispy-pork", "he-sushi", "sancun-shejian"] },
      { type: "散步小食", title: "礁溪香腸伯 ／ 蘭陽肉捲 ／ 舊路青草臭豆腐", note: "湯圍溝散步路上順手買。舊路青草臭豆腐是 DUDU FAMILY 在地人篇的第一名開場。", refs: ["jiaoxi-sausage-bo", "lanyang-meat-roll", "jiulu-stinky-tofu"] },
      { type: "宵夜", title: "飯店免費宵夜（18:00 起）", note: "現煮義大利麵、關東煮、甜點、蔬菜、餅乾零嘴，不用另外花錢出門覓食。**B 組晚上才到，晚餐直接在這裡吃**；若想吃熱食正餐，礁溪路上多數小吃營業到 21:00–22:00。" },
    ],
    categories: ["breakfast", "lunch", "dinner", "snack"],
  },
  {
    day: 2,
    date: "2026-09-19",
    dow: "六",
    city: "宜蘭・頭城 ／ 羅東",
    theme: "頭城海線・蘭陽博物館・羅東夜市爆吃",
    summary: "飯店早餐後往北走頭城海線：外澳沙灘正對龜山島、蘭陽博物館單面山建築（週六正常開館），中午鑽進 200 年的頭城老街吃小吃。下午回礁溪泡湯午休喘口氣，傍晚開車去**羅東夜市**照著內內的 18 間清單掃街，晚上回礁溪再泡一次溫泉。",
    level: "💰💰",
    timeline: [
      { time: "07:30", event: "🥐 飯店早餐 buffet（06:30–11:00 供應，慢慢吃）" },
      { time: "09:00", event: "🚗 出發往頭城（台２線濱海或台９線，約 15 分）" },
      { time: "09:30", event: "🌊 外澳沙灘／伯朗咖啡城堡 — 正對龜山島，海景與飛行傘起降點，散步拍照", refs: ["外澳沙灘與伯朗咖啡城堡"] },
      { time: "10:30", event: "🎨 蘭陽博物館（烏石港旁，單面山建築）— **週三休館，9/19 週六正常開放**，有收費停車場", refs: ["蘭陽博物館"] },
      { time: "12:00", event: "🏮 頭城老街（和平街）散步：源合成商號、陳春記商號、盧纘祥公館、頭城十三行、南北門福德祠「街頭街尾土地公」", refs: ["頭城老街"] },
      { time: "12:30", event: "🍜 午餐：品誼古早味小吃（沙成路50號，**週二、三公休**，週六 OK）or 綵宸小吃", refs: ["pinyi-snack", "caichen-snack"] },
      { time: "13:30", event: "🧋 飯後：阿宗芋冰城（青雲路三段267號）or 阿嬤蔥油餅（三和路18號）", refs: ["azong-taro-ice", "ama-scallion-pancake"] },
      { time: "14:30", event: "☕ 里海咖啡（食尚玩家推薦，咖啡廳裡有鮮魚料理）or 戶室山日式刨冰降溫", refs: ["lihai-coffee", "hushishan-shaved-ice"] },
      { time: "15:30", event: "🏨 回飯店午休泡湯（下午茶時段順便吃豆花）" },
      { time: "17:00", event: "🚗 出發羅東（台９線或國５宜蘭交流道，約 25–30 分）— 週末車位難找，建議停羅東林業文化園區或周邊收費停車場" },
      { time: "17:45", event: "🧋 **羅東夜市掃街**（民權路／公園路／民生路三條主街）：阿灶伯當歸羊肉湯 → 財哥龍鳳腿 → 嘟好燒 → 58石磨玉米餅 → 玉本舖三星蔥餅", refs: ["azaobo-lamb-soup", "caige-longfengtui", "duhaoshao", "stone-mill-corn-cake-58", "yubenpu-scallion-cake"] },
      { time: "19:00", event: "🧋 第二輪：黃師傅三星糕渣卜肉 → 宜蘭鄭記潤餅 → 上賓滷肉飯 → 小丙花生捲冰淇淋收尾", refs: ["huangshifu-zhabu", "zhengji-runbing", "shangbin-luroufan", "xiaobing-peanut-icecream"] },
      { time: "20:30", event: "🚗 開回礁溪（約 30 分）" },
      { time: "21:30", event: "♨️ 泡溫泉＋悅讀屋看漫畫（吃太飽的話宵夜就跳過）" },
    ],
    meals: [
      { type: "早餐", title: "飯店早餐 buffet", note: "06:30–11:00，已含在房價。想在外面吃的話，頭城老張早餐吧 05:00–13:30（**週四公休**，週六 OK）。", refs: ["laozhang-breakfast"] },
      { type: "午餐", title: "頭城老街小吃：品誼古早味 ／ 綵宸小吃", note: "三歲半頭城專集的名單。品誼週二、三公休；綵宸 11:00–14:00、16:30–20:30 分兩段營業，過了 14:00 就要等晚餐時段。", refs: ["pinyi-snack", "caichen-snack"] },
      { type: "下午茶", title: "里海咖啡 ／ 戶室山日式刨冰", note: "戶室山是食尚玩家與 DUDU FAMILY 都點名的高顏值日系刨冰；9 月下午還有 31–32 度，刨冰很實用。", refs: ["lihai-coffee", "hushishan-shaved-ice"] },
      { type: "夜市", title: "羅東夜市 九連吃", note: "路線照內內 Dc8lRnLbBv4 的地址走：興東路 → 民生路 → 公園路 → 民權路，一條龍不回頭。兩人建議每攤點一份分著吃，不然撐不到第五攤。阿灶伯當歸羊肉湯是 Patrick Fit 與內內雙推的在地招牌。", refs: ["azaobo-lamb-soup", "caige-longfengtui", "duhaoshao", "stone-mill-corn-cake-58", "yubenpu-scallion-cake", "huangshifu-zhabu", "zhengji-runbing", "shangbin-luroufan", "xiaobing-peanut-icecream", "longxin-yichuanxin"] },
    ],
    categories: ["breakfast", "lunch", "snack", "cafe"],
  },
  {
    day: 3,
    date: "2026-09-20",
    dow: "日",
    city: "宜蘭・礁溪",
    theme: "礁溪慢活・買伴手禮・傍晚吃飽北返",
    summary: "最後一天完全放慢。早餐後散步礁溪公園，11:00 前退房（行李直接放車上），中午吃陋室酩神粥府，下午定邦咖啡看山景、潭酵天地買伴手禮。傍晚再泡一次湯圍溝足湯，晚餐吃來益魚行海燒，吃飽再上路。**四人同車符合高乘載門檻，回程時間自由**，排在傍晚走只是為了避開週日下午雪隧最塞的那幾個小時。",
    level: "💰",
    timeline: [
      { time: "08:00", event: "🥐 飯店早餐 buffet（最後一次，吃飽一點）" },
      { time: "09:30", event: "🌳 礁溪公園散步（就在飯店隔壁）＋ 森林風呂區走走", refs: ["礁溪溫泉公園"] },
      { time: "10:45", event: "🏨 **退房（11:00 前）** — 行李直接放車上，車可先停飯店或礁溪路周邊" },
      { time: "11:30", event: "🥐 早午餐補一攤：礁溪包子饅頭（寧願被開罰單也要買到）or 美香齋雞蛋吐司", refs: ["jiaoxi-baozi", "meixiangzhai-toast"] },
      { time: "12:30", event: "🍜 午餐：陋室酩神粥府（礁溪路六段13巷5號）— 瑄瑄&G先生說「太愛的粥品」；或鐘氏肉羹（得獎肉羹）", refs: ["loushi-congee", "zhongshi-rougeng"] },
      { time: "14:00", event: "☕ 定邦咖啡（白雲二路173號，半山腰視野）看蘭陽平原；或阿冰哥豆腐腦、秀蘭阿姨泡泡冰", refs: ["dingbang-coffee", "abinge-tofu", "xiulan-bubble-ice"] },
      { time: "15:30", event: "🎁 潭酵天地買伴手禮（觀光工廠，室內、下雨也 OK）；想多帶點就順路奶油麵包礁溪旗艦店（**晚來買不到**）", refs: ["潭酵天地觀光工廠", "butter-bread-jiaoxi"] },
      { time: "17:00", event: "♨️ 最後一次湯圍溝免費足湯，把腳泡舒服再上路", refs: ["湯圍溝溫泉公園"] },
      { time: "18:00", event: "🍲 晚餐：來益魚行海燒（魚舖轉型的海鮮燒烤，食尚玩家＋非凡大探索雙推）or 添喜海鮮小吃", refs: ["laiyi-fish-grill", "tianxi-seafood"] },
      { time: "19:45", event: "🚗 往礁溪交流道移動（四人同車，不受高乘載管制限制）" },
      { time: "20:00", event: "🛣️ **國５北上** — 週日尖峰（16:00–19:00）已過，路況通常順暢" },
      { time: "21:00", event: "🏠 抵達台北，B 組可從台北市區轉乘回文化大學" },
    ],
    meals: [
      { type: "早餐", title: "飯店早餐 buffet ＋ 礁溪包子饅頭", note: "包子饅頭是 CHILL先生一家人「寧願被開罰單也要買到」的那家，可以買了路上吃或帶回台北。MORRIS健康廚房則是評論說最好吃的礁溪早午餐。", refs: ["jiaoxi-baozi", "meixiangzhai-toast", "morris-kitchen"] },
      { type: "午餐", title: "陋室酩神粥府 ／ 鐘氏肉羹", note: "粥府是瑄瑄&G先生私藏名單；鐘氏肉羹是得獎的礁溪肉羹。兩家都清爽，配合晚上還要吃海鮮燒烤。", refs: ["loushi-congee", "zhongshi-rougeng"] },
      { type: "下午茶", title: "定邦咖啡（山景）", note: "在白雲二路半山腰，可以坐著看蘭陽平原耗掉一個下午 — 反正 20:00 前不趕著走。", refs: ["dingbang-coffee"] },
      { type: "晚餐", title: "來益魚行海燒", note: "原本是魚舖，轉型做海鮮燒烤，食尚玩家 52:08 與非凡大探索都做過專題。吃完剛好 19:45 出發上國５。建議先訂位。", refs: ["laiyi-fish-grill", "tianxi-seafood"] },
    ],
    categories: ["breakfast", "lunch", "dinner", "cafe", "snack"],
  },
];

const CATEGORIES = {
  breakfast: { label: "早餐／早午餐", icon: "🥐" },
  lunch: { label: "午餐", icon: "🍜" },
  dinner: { label: "晚餐", icon: "🍲" },
  snack: { label: "小吃／夜市", icon: "🧋" },
  cafe: { label: "咖啡甜點冰品", icon: "☕" },
};

const RESTAURANTS = [
  // ============ 礁溪 ============
  {
    id: "keshi-scallion-pancake",
    name: "礁溪柯氏蔥油餅",
    city: "宜蘭",
    category: "breakfast",
    area: "礁溪",
    address: "宜蘭縣礁溪鄉礁溪路四段 128 號",
    days: [1, 3],
    price: "NT$30-60/人",
    must_try: ["蔥油餅加蛋", "辣椒醬"],
    note: "礁溪排隊第一名。第一代老闆娘被稱為「蔥油餅祖師娘」，免費教過許多辛苦人家做餅，第二代姊弟接手。現點現做、三星蔥爆汁，11:00 後常排 30 分鐘，**早點到最省時間**。",
    youtube: [
      { id: "xkpuqYdIfUU", creator: "台灣Cheers" },
      { id: "ZVy-UINBfmg", time: "01:47", creator: "DUDU FAMILY生活誌" },
    ],
  },
  {
    id: "wuji-peanut-roll",
    name: "吳記花生捲冰淇淋",
    city: "宜蘭",
    category: "snack",
    area: "礁溪",
    address: "宜蘭縣礁溪鄉礁溪路五段 141 號",
    days: [1],
    price: "NT$40-70/人",
    must_try: ["花生捲冰淇淋（加香菜）", "不加香菜版"],
    note: "宜蘭名產：現刨花生糖粉＋冰淇淋＋香菜，用春餅皮捲起來。與柯氏蔥油餅步行 3 分鐘，一起吃剛好。怕香菜可以請老闆不加。",
    youtube: [
      { id: "ZVy-UINBfmg", time: "02:49", creator: "DUDU FAMILY生活誌" },
    ],
  },
  {
    id: "sanmin-restaurant",
    name: "三民大飯店",
    city: "宜蘭",
    category: "lunch",
    area: "礁溪",
    address: "宜蘭縣礁溪鄉礁溪路五段 108 號",
    days: [1],
    price: "NT$300-600/人",
    must_try: ["桶仔雞", "蔥爆牛肉", "三星蔥蛋"],
    note: "名字叫大飯店，其實是礁溪熱炒老店。CHILL先生一家人說「來了很多次從來都沒有排到」，**中午建議先打電話**。",
    youtube: [
      { id: "4g5hr4YLSJ4", time: "17:45", creator: "CHILL先生一家人" },
    ],
  },
  {
    id: "fuge-stone-kiln-chicken",
    name: "福哥石窯雞",
    city: "宜蘭",
    category: "lunch",
    area: "礁溪",
    address: "宜蘭縣礁溪鄉",
    days: [1],
    price: "NT$700-900/隻",
    must_try: ["石窯烤雞（原味）"],
    note: "烤雞達人「福哥」逐溫泉而居，從北投、烏來一路落腳礁溪，一天賣好幾百隻，外酥內嫩吃原味。兩人吃半隻剛好。",
    youtube: [
      { id: "xkpuqYdIfUU", time: "08:21", creator: "台灣Cheers" },
    ],
  },
  {
    id: "laijia-noodle",
    name: "賴家手工雙醬麵",
    city: "宜蘭",
    category: "lunch",
    area: "礁溪",
    address: "宜蘭縣礁溪鄉",
    days: [1],
    price: "NT$60-120/人",
    must_try: ["雙醬麵", "小菜"],
    note: "CHILL先生一家人礁溪八選的開場店，手工雙醬拌麵，銅板價快速解決一餐。",
    youtube: [
      { id: "4g5hr4YLSJ4", time: "00:43", creator: "CHILL先生一家人" },
    ],
  },
  {
    id: "taiyi-crispy-pork",
    name: "太一脆皮五花肉",
    city: "宜蘭",
    category: "dinner",
    area: "礁溪",
    address: "宜蘭縣礁溪鄉中山路二段 56 號",
    days: [1],
    price: "NT$300-600/人",
    must_try: ["脆皮五花肉"],
    note: "瑄瑄&G先生私藏 5 間之一，形容「頂天的脆皮五花肉」。地址在中山路二段，離礁溪路main street 一小段，開車 3 分鐘。",
    youtube: [
      { id: "jX4WKHH_TJU", creator: "瑄瑄 & G先生" },
    ],
  },
  {
    id: "sancun-shejian",
    name: "三寸舌尖",
    city: "宜蘭",
    category: "dinner",
    area: "礁溪",
    address: "宜蘭縣礁溪鄉",
    days: [1],
    price: "NT$600-1200/人",
    must_try: ["主廚推薦套餐"],
    note: "食尚玩家礁溪必吃清單第二站，屬於比較講究的餐廳型選擇。想把 Day 1 晚餐升級時的首選，**需訂位**。",
    youtube: [
      { id: "eKeif8H65Yo", time: "05:10", creator: "食尚玩家" },
    ],
  },
  {
    id: "he-sushi",
    name: "和壽司",
    city: "宜蘭",
    category: "dinner",
    area: "礁溪",
    address: "宜蘭縣礁溪鄉",
    days: [1, 3],
    price: "NT$400-900/人",
    must_try: ["生魚片", "握壽司"],
    note: "DUDU FAMILY 在地人帶路篇的壓軸。想吃日式、清爽一點時的選項，**建議訂位**。",
    youtube: [
      { id: "ZVy-UINBfmg", time: "06:05", creator: "DUDU FAMILY生活誌" },
    ],
  },
  {
    id: "jiaoxi-sausage-bo",
    name: "礁溪香腸伯（分店）",
    city: "宜蘭",
    category: "snack",
    area: "礁溪",
    address: "宜蘭縣礁溪鄉礁溪路五段 1-1 號",
    days: [1],
    price: "NT$30-80/人",
    must_try: ["炭烤香腸", "蒜頭"],
    note: "瑄瑄&G先生名單。礁溪路上邊走邊吃的經典，散步去湯圍溝的路上順手買。",
    youtube: [
      { id: "jX4WKHH_TJU", creator: "瑄瑄 & G先生" },
    ],
  },
  {
    id: "lanyang-meat-roll",
    name: "蘭陽肉捲",
    city: "宜蘭",
    category: "snack",
    area: "礁溪",
    address: "宜蘭縣礁溪鄉",
    days: [1],
    price: "NT$40-90/人",
    must_try: ["炸肉捲"],
    note: "DUDU FAMILY 在地人推薦，宜蘭特色炸肉捲，現炸現吃最酥。",
    youtube: [
      { id: "ZVy-UINBfmg", time: "03:27", creator: "DUDU FAMILY生活誌" },
    ],
  },
  {
    id: "jiulu-stinky-tofu",
    name: "舊路青草臭豆腐",
    city: "宜蘭",
    category: "snack",
    area: "礁溪",
    address: "宜蘭縣礁溪鄉",
    days: [1],
    price: "NT$50-100/人",
    must_try: ["青草臭豆腐", "泡菜"],
    note: "DUDU FAMILY「在地人帶路」影片的開場第一家，用青草滷製，在地評價高於觀光客名店。",
    youtube: [
      { id: "ZVy-UINBfmg", time: "00:24", creator: "DUDU FAMILY生活誌" },
    ],
  },
  {
    id: "butter-bread-jiaoxi",
    name: "奶油麵包（礁溪旗艦店）",
    city: "宜蘭",
    category: "snack",
    area: "礁溪",
    address: "宜蘭縣礁溪鄉",
    days: [1, 3],
    price: "NT$40-80/個",
    must_try: ["招牌奶油麵包"],
    note: "食尚玩家整集的開場第一名：**晚來買不到**。適合 Day 3 離開前買來當伴手禮或路上吃，建議上午就先買。",
    youtube: [
      { id: "eKeif8H65Yo", time: "00:00", creator: "食尚玩家" },
    ],
  },
  {
    id: "hushishan-shaved-ice",
    name: "戶室山日式刨冰",
    city: "宜蘭",
    category: "cafe",
    area: "礁溪",
    address: "宜蘭縣礁溪鄉",
    days: [2],
    price: "NT$150-250/份",
    must_try: ["季節水果刨冰", "宇治金時"],
    note: "食尚玩家與 DUDU FAMILY **雙推**的高顏值日系刨冰。9 月下午還有 31–32°C，走完老街來一碗剛好。",
    youtube: [
      { id: "eKeif8H65Yo", time: "11:49", creator: "食尚玩家" },
      { id: "ZVy-UINBfmg", time: "04:55", creator: "DUDU FAMILY生活誌" },
    ],
  },
  {
    id: "lihai-coffee",
    name: "里海咖啡",
    city: "宜蘭",
    category: "cafe",
    area: "礁溪",
    address: "宜蘭縣礁溪鄉",
    days: [2],
    price: "NT$250-500/人",
    must_try: ["鮮魚料理", "手沖咖啡"],
    note: "食尚玩家形容「咖啡廳裡有鮮魚料理」。不只喝咖啡，餐點是賣點，可以當正餐吃。",
    youtube: [
      { id: "eKeif8H65Yo", time: "35:38", creator: "食尚玩家" },
    ],
  },
  {
    id: "xiaoshiba",
    name: "小食粑",
    city: "宜蘭",
    category: "snack",
    area: "礁溪",
    address: "宜蘭縣礁溪鄉",
    days: [3],
    price: "NT$50-150/人",
    must_try: ["麻糬類點心"],
    note: "食尚玩家礁溪清單第四站，小巧的在地點心店。",
    youtube: [
      { id: "eKeif8H65Yo", time: "18:03", creator: "食尚玩家" },
    ],
  },
  {
    id: "laiyi-fish-grill",
    name: "來益魚行海燒",
    city: "宜蘭",
    category: "dinner",
    area: "礁溪",
    address: "宜蘭縣礁溪鄉",
    days: [3],
    price: "NT$500-900/人",
    must_try: ["炭烤現流魚", "烤蛤蜊", "海鮮拼盤"],
    note: "🔒 **Day 3 晚餐主場**。原本是魚舖，轉型做海鮮燒烤，食尚玩家（52:08）與非凡大探索都做過專題 — 自家魚舖進貨，新鮮度是賣點。吃完剛好 19:45 出發上國５。**建議先訂位**。",
    youtube: [
      { id: "eKeif8H65Yo", time: "52:08", creator: "食尚玩家" },
      { id: "lMsDlFYAx2c", creator: "非凡大探索" },
    ],
  },
  {
    id: "tianxi-seafood",
    name: "添喜海鮮小吃",
    city: "宜蘭",
    category: "dinner",
    area: "礁溪",
    address: "宜蘭縣礁溪鄉",
    days: [3],
    price: "NT$300-600/人",
    must_try: ["現撈海鮮", "熱炒"],
    note: "非凡大探索專題「礁溪高CP值海鮮小吃」。來益魚行訂不到位時的替代方案，價格更親民。",
    youtube: [
      { id: "C699woV6Eks", creator: "非凡大探索" },
    ],
  },
  {
    id: "loushi-congee",
    name: "陋室酩神粥府",
    city: "宜蘭",
    category: "lunch",
    area: "礁溪",
    address: "宜蘭縣礁溪鄉礁溪路六段 13 巷 5 號",
    days: [3],
    price: "NT$200-400/人",
    must_try: ["招牌粥品", "小菜"],
    note: "瑄瑄&G先生「太愛的粥品」。Day 3 中午吃清爽的，才吃得下晚上的海鮮燒烤。",
    youtube: [
      { id: "jX4WKHH_TJU", creator: "瑄瑄 & G先生" },
    ],
  },
  {
    id: "zhongshi-rougeng",
    name: "鐘氏肉羹",
    city: "宜蘭",
    category: "lunch",
    area: "礁溪",
    address: "宜蘭縣礁溪鄉",
    days: [3],
    price: "NT$60-120/人",
    must_try: ["肉羹", "肉羹麵"],
    note: "CHILL先生一家人介紹的**得獎肉羹**。礁溪在地銅板午餐。",
    youtube: [
      { id: "4g5hr4YLSJ4", time: "22:00", creator: "CHILL先生一家人" },
    ],
  },
  {
    id: "jiaoxi-baozi",
    name: "礁溪包子饅頭",
    city: "宜蘭",
    category: "breakfast",
    area: "礁溪",
    address: "宜蘭縣礁溪鄉",
    days: [3],
    price: "NT$20-60/個",
    must_try: ["肉包", "饅頭"],
    note: "CHILL先生一家人形容「寧願被開罰單也要買到的包子饅頭」（店門口不好停車，這是重點提醒）。可買一袋帶回台北。",
    youtube: [
      { id: "4g5hr4YLSJ4", time: "12:57", creator: "CHILL先生一家人" },
    ],
  },
  {
    id: "meixiangzhai-toast",
    name: "美香齋雞蛋吐司",
    city: "宜蘭",
    category: "breakfast",
    area: "礁溪",
    address: "宜蘭縣礁溪鄉",
    days: [3],
    price: "NT$40-80/份",
    must_try: ["雞蛋吐司"],
    note: "CHILL先生一家人說「香到沒朋友的雞蛋吐司」。古早味碳烤吐司，早上排隊。",
    youtube: [
      { id: "4g5hr4YLSJ4", time: "31:53", creator: "CHILL先生一家人" },
    ],
  },
  {
    id: "morris-kitchen",
    name: "MORRIS健康廚房",
    city: "宜蘭",
    category: "breakfast",
    area: "礁溪",
    address: "宜蘭縣礁溪鄉",
    days: [3],
    price: "NT$200-350/人",
    must_try: ["早午餐套餐"],
    note: "CHILL先生一家人說「評論裡說最好吃的礁溪早午餐」。想吃坐下來的西式早午餐時選這家。",
    youtube: [
      { id: "4g5hr4YLSJ4", time: "08:06", creator: "CHILL先生一家人" },
    ],
  },
  {
    id: "dingbang-coffee",
    name: "定邦咖啡",
    city: "宜蘭",
    category: "cafe",
    area: "礁溪白雲路（半山腰）",
    address: "宜蘭縣礁溪鄉白雲二路 173 號",
    days: [3],
    price: "NT$200-400/人",
    must_try: ["手沖咖啡", "甜點"],
    note: "瑄瑄&G先生名單。在白雲二路半山腰，可以坐著俯瞰蘭陽平原耗一個下午 — Day 3 反正 20:00 前不趕著走，很適合。**山路彎，開車慢一點**。",
    youtube: [
      { id: "jX4WKHH_TJU", creator: "瑄瑄 & G先生" },
    ],
  },
  {
    id: "abinge-tofu",
    name: "阿冰哥豆腐腦",
    city: "宜蘭",
    category: "cafe",
    area: "礁溪",
    address: "宜蘭縣礁溪鄉",
    days: [3],
    price: "NT$50-100/碗",
    must_try: ["豆腐腦", "豆花"],
    note: "CHILL先生一家人名單。傳統豆腐腦，天熱時比咖啡更解渴。",
    youtube: [
      { id: "4g5hr4YLSJ4", time: "28:40", creator: "CHILL先生一家人" },
    ],
  },
  {
    id: "xiulan-bubble-ice",
    name: "秀蘭阿姨泡泡冰",
    city: "宜蘭",
    category: "snack",
    area: "礁溪",
    address: "宜蘭縣礁溪鄉",
    days: [3],
    price: "NT$50-90/份",
    must_try: ["花生泡泡冰", "情人果泡泡冰"],
    note: "CHILL先生一家人名單。現打綿密泡泡冰，走完礁溪公園來一碗。",
    youtube: [
      { id: "4g5hr4YLSJ4", time: "30:38", creator: "CHILL先生一家人" },
    ],
  },

  // ============ 頭城（Day 2 上午） ============
  {
    id: "laozhang-breakfast",
    name: "老張早餐吧",
    city: "宜蘭",
    category: "breakfast",
    area: "頭城老街",
    address: "宜蘭縣頭城鎮和平街 92 號",
    days: [2],
    price: "NT$40-100/人",
    must_try: ["古早味蛋餅", "豆漿"],
    note: "05:00–13:30 營業，**週四公休**（9/19 週六正常）。就在頭城老街上，若不想吃飯店 buffet 可以來這家。",
    youtube: [
      { id: "h0LDCVoSoV8", creator: "三歲半 Three Age Half" },
    ],
  },
  {
    id: "pinyi-snack",
    name: "品誼古早味小吃",
    city: "宜蘭",
    category: "lunch",
    area: "頭城",
    address: "宜蘭縣頭城鎮城北里沙成路 50 號",
    days: [2],
    price: "NT$60-150/人",
    must_try: ["米粉羹", "古早味小吃"],
    note: "三歲半頭城專集裡「在地人激推米粉羹必排隊」的那家。10:30–18:00，**週二、三公休**（9/19 週六 OK）。",
    youtube: [
      { id: "h0LDCVoSoV8", creator: "三歲半 Three Age Half" },
    ],
  },
  {
    id: "caichen-snack",
    name: "綵宸小吃",
    city: "宜蘭",
    category: "lunch",
    area: "頭城",
    address: "宜蘭縣頭城鎮開蘭路 103 號",
    days: [2],
    price: "NT$80-200/人",
    must_try: ["在地熱炒小吃"],
    note: "11:00–14:00 / 16:30–20:30 分兩段營業，**過了 14:00 就要等到傍晚**，中午別拖太晚。",
    youtube: [
      { id: "h0LDCVoSoV8", creator: "三歲半 Three Age Half" },
    ],
  },
  {
    id: "azong-taro-ice",
    name: "阿宗芋冰城",
    city: "宜蘭",
    category: "snack",
    area: "頭城",
    address: "宜蘭縣頭城鎮青雲路三段 267 號",
    days: [2],
    price: "NT$40-80/份",
    must_try: ["芋頭冰", "花生冰"],
    note: "09:00–21:00，時間彈性大。頭城老牌芋冰，逛完老街的固定收尾。",
    youtube: [
      { id: "h0LDCVoSoV8", creator: "三歲半 Three Age Half" },
    ],
  },
  {
    id: "ama-scallion-pancake",
    name: "阿嬤蔥油餅",
    city: "宜蘭",
    category: "snack",
    area: "頭城",
    address: "宜蘭縣頭城鎮三和路 18 號",
    days: [2],
    price: "NT$30-60/份",
    must_try: ["蔥油餅"],
    note: "08:00–18:00。頭城版的蔥油餅，與礁溪柯氏可以比較一下誰勝出。",
    youtube: [
      { id: "h0LDCVoSoV8", creator: "三歲半 Three Age Half" },
    ],
  },

  // ============ 羅東夜市（Day 2 晚上） ============
  {
    id: "azaobo-lamb-soup",
    name: "阿灶伯當歸羊肉湯",
    city: "宜蘭",
    category: "snack",
    area: "羅東夜市",
    address: "宜蘭縣羅東鎮民權路 265 號",
    days: [2],
    price: "NT$100-200/人",
    must_try: ["當歸羊肉湯", "羊肉麵線"],
    note: "🔒 **羅東夜市第一站**。內內與 Patrick Fit **雙推**的在地招牌，當歸香濃、羊肉不腥。先喝湯墊胃再開始掃街。",
    youtube: [
      { id: "Dc8lRnLbBv4", time: "19:07", creator: "內內 Nene" },
      { id: "AdGJP6skgjk", creator: "Patrick Fit" },
    ],
  },
  {
    id: "caige-longfengtui",
    name: "財哥龍鳳腿",
    city: "宜蘭",
    category: "snack",
    area: "羅東夜市",
    address: "宜蘭縣羅東鎮民生路 16 號",
    days: [2],
    price: "NT$40-80/份",
    must_try: ["龍鳳腿"],
    note: "宜蘭獨有小吃：豆皮包魚漿與蔬菜下鍋炸，外型像雞腿。內內 04:51。",
    youtube: [
      { id: "Dc8lRnLbBv4", time: "04:51", creator: "內內 Nene" },
    ],
  },
  {
    id: "duhaoshao",
    name: "嘟好燒",
    city: "宜蘭",
    category: "snack",
    area: "羅東夜市",
    address: "宜蘭縣羅東鎮民生路 12 號",
    days: [2],
    price: "NT$30-60/份",
    must_try: ["紅豆嘟好燒"],
    note: "宜蘭古早味炸甜點，外酥內軟包紅豆。與財哥龍鳳腿只隔兩個門牌，一起吃。",
    youtube: [
      { id: "Dc8lRnLbBv4", time: "05:47", creator: "內內 Nene" },
    ],
  },
  {
    id: "stone-mill-corn-cake-58",
    name: "58石磨玉米餅",
    city: "宜蘭",
    category: "snack",
    area: "羅東夜市",
    address: "宜蘭縣羅東鎮公園路 148 號",
    days: [2],
    price: "NT$50-90/份",
    must_try: ["牽絲玉米餅"],
    note: "內內影片標題點名的「牽絲玉米餅」，現烤起司會拉絲。",
    youtube: [
      { id: "Dc8lRnLbBv4", time: "09:04", creator: "內內 Nene" },
    ],
  },
  {
    id: "yubenpu-scallion-cake",
    name: "玉本舖三星蔥餅",
    city: "宜蘭",
    category: "snack",
    area: "羅東夜市",
    address: "宜蘭縣羅東鎮民權路 85 號",
    days: [2],
    price: "NT$40-80/份",
    must_try: ["三星蔥餅"],
    note: "內內標題的「爆炸三星蔥餅」，三星蔥爆量。",
    youtube: [
      { id: "Dc8lRnLbBv4", time: "12:17", creator: "內內 Nene" },
    ],
  },
  {
    id: "huangshifu-zhabu",
    name: "黃師傅三星糕渣卜肉",
    city: "宜蘭",
    category: "snack",
    area: "羅東夜市",
    address: "宜蘭縣羅東鎮民權路 1109 號攤位",
    days: [2],
    price: "NT$60-120/份",
    must_try: ["糕渣", "卜肉"],
    note: "糕渣與卜肉是宜蘭傳統辦桌菜的代表，糕渣「外冷內熱」要小心燙口。",
    youtube: [
      { id: "Dc8lRnLbBv4", time: "12:18", creator: "內內 Nene" },
    ],
  },
  {
    id: "zhengji-runbing",
    name: "宜蘭鄭記潤餅",
    city: "宜蘭",
    category: "snack",
    area: "羅東夜市",
    address: "宜蘭縣羅東鎮民權路 265 號（羅東夜市 1101 號攤）",
    days: [2],
    price: "NT$50-90/份",
    must_try: ["潤餅捲"],
    note: "內內稱「60年老店潤餅」。就在阿灶伯羊肉湯同一個門牌區，順路。",
    youtube: [
      { id: "Dc8lRnLbBv4", time: "16:37", creator: "內內 Nene" },
    ],
  },
  {
    id: "shangbin-luroufan",
    name: "上賓滷肉飯",
    city: "宜蘭",
    category: "snack",
    area: "羅東夜市",
    address: "宜蘭縣羅東鎮民權路 87 號",
    days: [2],
    price: "NT$40-100/人",
    must_try: ["滷肉飯", "滷蛋"],
    note: "內內 18 間裡的壓軸。若前面吃太多小吃，這攤可以只點一小碗分著吃。",
    youtube: [
      { id: "Dc8lRnLbBv4", time: "20:53", creator: "內內 Nene" },
    ],
  },
  {
    id: "xiaobing-peanut-icecream",
    name: "小丙花生捲冰淇淋",
    city: "宜蘭",
    category: "snack",
    area: "羅東夜市",
    address: "宜蘭縣羅東鎮公園路 162 號",
    days: [2],
    price: "NT$40-70/份",
    must_try: ["花生捲冰淇淋"],
    note: "羅東版的花生捲冰淇淋，當作掃街的甜點收尾。",
    youtube: [
      { id: "Dc8lRnLbBv4", time: "07:52", creator: "內內 Nene" },
    ],
  },
  {
    id: "longxin-yichuanxin",
    name: "隆新一串心",
    city: "宜蘭",
    category: "snack",
    area: "羅東夜市",
    address: "宜蘭縣羅東鎮興東路 8 號",
    days: [2],
    price: "NT$30-70/份",
    must_try: ["一串心（豆皮夾料）"],
    note: "內內的第一站（03:49），在興東路上，剛好是從停車場走進夜市的入口方向。",
    youtube: [
      { id: "Dc8lRnLbBv4", time: "03:49", creator: "內內 Nene" },
    ],
  },
  {
    id: "linchang-rougeng",
    name: "林場肉羹",
    city: "宜蘭",
    category: "lunch",
    area: "羅東",
    address: "宜蘭縣羅東鎮中正北路 109 號",
    days: [2],
    price: "NT$60-120/人",
    must_try: ["肉羹", "米糕"],
    note: "羅東最有名的肉羹老店（在林業文化園區附近，不在夜市內）。Patrick Fit 點名。若提早到羅東可以先吃這攤，注意**下午就收**。",
    youtube: [
      { id: "AdGJP6skgjk", creator: "Patrick Fit" },
    ],
  },
];

const TRANSPORT = {
  sections: [
    {
      icon: "🚌",
      title: "9/18 文化大學 → 礁溪（B 組 1 人，18:00 出發）",
      type: "options",
      items: [
        {
          name: "① 紅5／小15 → 捷運 → 葛瑪蘭 1915（推薦）",
          time: "約 2–2.5 小時",
          fare: "約 NT$160",
          note: "文化大學搭紅5 或小15 下山到**劍潭捷運站**（25–40 分，仰德大道傍晚會塞）→ 淡水信義線到**台北車站**（3 站約 8 分）→ 步行 5–10 分到**台北轉運站**（市民大道上）→ 搭**葛瑪蘭客運 1915**（台北→礁溪→宜蘭→羅東），台北到礁溪全票 NT$112 → 在**礁溪轉運站**下車。轉乘最單純、班次也密。",
        },
        {
          name: "② 紅5／小15 → 捷運 → 首都 1572",
          time: "約 2–2.5 小時",
          fare: "約 NT$160",
          note: "同樣先到劍潭，改搭捷運到**市政府站**（需在忠孝復興轉板南線）→ **市府轉運站**搭**首都客運 1572**（市府→礁溪→宜蘭→羅東）。班距平日尖峰 10–15 分、離峰 15–20 分，假日全天 10–20 分，班次比 1915 更密；但捷運要多轉一次線。",
        },
        {
          name: "③ 260 公車直達台北車站",
          time: "約 2.5 小時",
          fare: "約 NT$130",
          note: "文化大學搭 **260** 直接到台北車站，不用轉捷運，但下山經仰德大道＋市區，週五傍晚較慢。到台北車站後一樣走到台北轉運站搭 1915。適合行李多、不想拖著上下捷運的人。",
        },
        {
          name: "④ 台鐵（備案，不建議週五）",
          time: "約 1 小時（車程）",
          fare: "自強 NT$150 起",
          note: "捷運到台北車站轉台鐵到**礁溪站**。車程最快，但**週五晚上東部幹線一票難求**，通常只剩無座票甚至買不到。除非事先訂到票，否則不要把它當主要方案。",
        },
      ],
      note: "⚠️ 週五傍晚（18:00–21:00）是國５南下壅塞尖峰，客運可能比平常多花 30–40 分鐘。抵達礁溪轉運站時間抓 20:30–21:30，A 組開車去接約 5 分鐘。末班車時間請以葛瑪蘭／首都客運官網為準。",
    },
    {
      icon: "✅",
      title: "國５週日北上高乘載管制（四人不受限）",
      type: "info-rows",
      items: [
        { key: "管制時間", val: "每週日 15:00–20:00（常態實施，非連假限定）" },
        { key: "管制路段", val: "國道５號**北上**：蘇澳、羅東、宜蘭、頭城 四個交流道的北上入口匝道" },
        { key: "門檻", val: "小客車須載滿 **3 人（含駕駛）以上**" },
        { key: "我們的狀況", val: "✅ **四人同車，符合門檻，不受限制** — 9/20 整天都可以上國５", wrap: true },
        { key: "但仍要避塞", val: "週日北上 10:00–20:00 容易塞，16:00–19:00 最嚴重。本趟排成傍晚吃飽再走（約 19:45 上匝道），避開最痛的時段", wrap: true },
        { key: "替代道路", val: "真的塞到不行可改台９線北宜公路（九彎十八拐），不受管制但山路彎、要 1 小時以上，夜間不建議", wrap: true },
      ],
      note: "資料來源：交通部高速公路局「國道5號週日15-20時常態實施北上高乘載管制」。違規者匝道直接攔阻，罰鍰 NT$3,000–6,000 — 這趟我們四人所以不受影響，但若有人臨時提早離開就要注意。",
    },
    {
      icon: "🚗",
      title: "自駕路線與車程",
      type: "table",
      items: [
        { route: "台北 → 礁溪", path: "國道１/３ → 南港系統 → 國道５ → 礁溪交流道", time: "50–60 分", fare: "過路費約 NT$120", note: "9/18 週五上午出發最順" },
        { route: "礁溪 → 猴洞坑瀑布", path: "台９線 → 白石腳路", time: "10 分", fare: "—", note: "無停車場，路邊白線停車" },
        { route: "猴洞坑 → 龍潭湖", path: "台９線南下", time: "15 分", fare: "—", note: "龍潭湖有免費停車場" },
        { route: "礁溪 → 頭城／烏石港", path: "台２線濱海 或 台９線", time: "15 分", fare: "—", note: "蘭陽博物館有收費停車場" },
        { route: "礁溪 → 羅東", path: "台９線 或 國５宜蘭交流道", time: "25–30 分", fare: "—", note: "週末夜市車位難找" },
        { route: "礁溪 → 台北（回程）", path: "礁溪交流道 → 國道５ 北上", time: "60 分", fare: "過路費約 NT$120", note: "⚠️ 週日 20:00 後再上" },
      ],
    },
    {
      icon: "🅿️",
      title: "各點停車資訊",
      type: "info-rows",
      items: [
        { key: "品文旅礁溪", val: "住宿附**免費停車位**，戶外停車場、車位多" },
        { key: "猴洞坑瀑布", val: "⚠️ **沒有停車場**，導航「白石腳路 196 號」後沿巷道白線找位子" },
        { key: "龍潭湖", val: "有免費停車場，空間大" },
        { key: "蘭陽博物館", val: "館方收費停車場" },
        { key: "頭城老街", val: "和平街旁路邊停車格，老街內窄不要開進去" },
        { key: "羅東夜市", val: "週末一位難求。建議停羅東林業文化園區或周邊收費停車場，走過去約 5–10 分", wrap: true },
        { key: "礁溪轉運站（接人用）", val: "9/18 晚上接 B 組的地點，站前可短暫停靠上下客，不要久停", wrap: true },
      ],
    },
    {
      icon: "🛣️",
      title: "雪隧壅塞時段（避開用）",
      type: "info-rows",
      items: [
        { key: "週五南下", val: "傍晚下班後最塞 → 本趟 9/18 上午 09:00 出發就避開了" },
        { key: "週日北上", val: "10:00–20:00 幾乎必塞，16:00–19:00 最嚴重" },
        { key: "順暢時", val: "台北 ↔ 礁溪 約 50–60 分鐘" },
        { key: "即時路況", val: "出發前查高公局 1968 App 或 tw.live 國道即時影像" },
      ],
    },
  ],
};

const TIPS = {
  sections: [
    {
      icon: "🌦️",
      title: "天氣（9/17 查詢的最新預報）",
      type: "info-rows",
      items: [
        { key: "整體", val: "**9/17 起東北季風減弱**，9/18–9/20 為偏東風至東北風" },
        { key: "降雨", val: "宜蘭有**局部短暫陣雨**，但相較 9/14–16 的增強期，雨勢明顯減弱" },
        { key: "氣溫", val: "高溫回到 **31–32°C**，偏熱" },
        { key: "判讀", val: "多雲到晴為主、偶有短暫陣雨 → **可以排戶外步道，但要帶雨具**", wrap: true },
        { key: "宜蘭 9 月", val: "日照時數全年第三（僅次 7、8 月），還算容易見到陽光；通常要到 10 月中下旬降雨才會明顯變多", wrap: true },
        { key: "出發前", val: "再查一次中央氣象署礁溪鄉鄉鎮預報", wrap: true },
      ],
    },
    {
      icon: "🥾",
      title: "步道開放狀況（出發前查證）",
      type: "reminders",
      items: [
        { title: "❌ 林美石磐步道 — 本趟期間封閉，不要去", body: "林務局台灣山林悠遊網官方公告：2026/9/14–9/24 暫停開放，施作拆換土木階梯與上邊坡危木作業，正好卡到這趟。另有長期公告：因坍方，2026 全年僅開放 0–0.9K，石磐瀑布所在的後段不開放。很多部落格還在推薦這條，去了會白跑。" },
        { title: "⚠️ 五峰旗瀑布步道 — 狀況不明，別排進主行程", body: "查到的公告是「配合復建工程，即日起至民國115年1月31日止不對外開放」（該期限已過），但另有遊記說第二層賞瀑平台上方坍方、第三層封閉，資訊互相矛盾。真的想去請先打礁溪鄉公所或到遊客中心問。遊客中心與停車場本身正常營運。" },
        { title: "✅ 猴洞坑瀑布 — 開放，本趟主步道", body: "全年開放免費、無需申請。入口導航「白石腳路196號」，沒有停車場要路邊白線停。10–15 分鐘登頂約 200 階，來回含停留 45–60 分。瀑布頂可俯瞰蘭陽平原、遠眺龜山島。注意：第二層瀑布的小平台目前封閉禁止跨越。雨後石階濕滑，穿防滑鞋。" },
        { title: "✅ 龍潭湖環湖步道 — 零陡坡，收尾用", body: "從遊客中心繞湖一圈回停車場不用一小時，全程平坦。有大碗公溜滑梯與大片草地，免費停車場。猴洞坑爬完之後走這段剛好緩和。" },
        { title: "🔁 備案：跑馬古道南段", body: "山徑寬闊、坡度平緩的碎石路，導航「礁溪鄉白石腳路157巷1號」南口 — 與猴洞坑同一條路，可以一併安排。全長 5 公里不必走完，走一小段折返即可。" },
      ],
    },
    {
      icon: "🎒",
      title: "打包清單",
      type: "checklist",
      items: [
        "輕便雨衣（山區步道撐傘不便，雨衣優先）＋ 折疊傘",
        "防滑健行鞋或運動鞋（猴洞坑石階雨後濕滑）",
        "泳衣（飯店有溫泉 SPA 水療與戲水池，大眾區需著泳裝）",
        "水壺 — 31–32°C ＋ 泡溫泉很容易脫水",
        "防曬乳、帽子、太陽眼鏡（外澳沙灘、環湖步道無遮蔭）",
        "薄外套（飯店冷氣、山區夜晚）",
        "行動電源",
        "零錢／小額現金（夜市與老街小攤多半不收行動支付）",
        "環保袋（買伴手禮：奶油麵包、礁溪包子饅頭）",
        "健保卡、駕照、行照",
        "B 組：悠遊卡／一卡通（公車＋捷運＋客運都能刷），手機開即時位置分享",
      ],
    },
    {
      icon: "📌",
      title: "訂位與時間提醒",
      type: "reminders",
      items: [
        { title: "🛏️ 入住時記得說有一位晚到", body: "✅ 訂房已確認為 4 人房型。9/18 A 組 3 人下午先 check in，**跟櫃檯說明晚上還有一位同行者會到**（約 21:00 前後），確認房卡份數與晚到入住方式；飯店最晚保留時間是 18:00，先辦好入住就不受影響。早餐 4 份、宵夜與下午茶都是住客免費。" },
        { title: "要先訂位的店", body: "三民大飯店（Day 1 午餐，中午常客滿）、來益魚行海燒（Day 3 晚餐，本趟晚餐主場）、三寸舌尖與和壽司（若要升級晚餐）。出發前一天打電話最保險。四人用餐比兩人更需要訂位。" },
        { title: "公休日已對過（都沒中）", body: "蘭陽博物館週三休 → 9/19 週六開。頭城品誼古早味週二、三公休 → 週六開。老張早餐吧週四公休 → 週六開。綵宸小吃 11:00–14:00／16:30–20:30 分兩段，中午別拖過 14:00。" },
        { title: "飯店免費餐飲別錯過", body: "早餐 06:30–11:00（已含）、下午茶豆花與紅酒無限、18:00 起免費宵夜（現煮義大利麵、關東煮、甜點）。Day 1 與 Day 2 傍晚都刻意留了回飯店的時間。" },
        { title: "晚來買不到的兩家", body: "奶油麵包（礁溪旗艦店）— 食尚玩家整集開場就強調晚來買不到；礁溪包子饅頭 — 賣完就收。要買請排在上午。" },
        { title: "Day 3 退房時間", body: "11:00 前退房。行李直接放車上，下午的行程（定邦咖啡、潭酵天地、湯圍溝）都不需要回飯店。" },
        { title: "9/18 晚上接人", body: "B 組 18:00 從文化大學出發，走「紅5／小15 → 劍潭 → 捷運 → 台北車站 → 台北轉運站 → 葛瑪蘭 1915」，預計 20:30–21:30 抵達礁溪轉運站。週五傍晚國５南下會塞，出發前先交換手機與即時位置，A 組開車去接只要 5 分鐘。B 組的晚餐可以留到飯店免費宵夜解決。" },
        { title: "回程高乘載：四人不受限", body: "國５週日 15:00–20:00 北上要滿 3 人，我們四人同車符合門檻，回程時間自由。排在傍晚走純粹是為了避開 16:00–19:00 的雪隧壅塞尖峰。" },
      ],
    },
    {
      icon: "🌧️",
      title: "雨天備案",
      type: "checklist",
      items: [
        "蘭陽博物館（室內，Day 2 原本就有排）",
        "潭酵天地（礁溪觀光工廠，可買伴手禮）",
        "金車生技水產養殖研發中心（礁溪，室內）",
        "飯店溫泉 SPA 水療 ＋ 悅讀屋看漫畫喝免費咖啡 ＋ 玩起來遊戲室",
        "湯圍溝公共湯屋（湯圍風呂，付費室內湯屋）",
        "改成純吃：礁溪美食清單有 20 家以上，雨天就一家家吃過去",
      ],
    },
  ],
};

const SIGHTS = [
  {
    name: "猴洞坑瀑布",
    city: "礁溪",
    day: 1,
    time: "13:00",
    address: "宜蘭縣礁溪鄉白石腳路 196 號附近",
    note: "🥾 **Day 1 主步道**。全年開放免費、免申請。入口到瀑布頂約 10–15 分鐘、約 200 階，來回含停留 45–60 分。瀑布頂景觀平台可俯瞰蘭陽平原、遠眺龜山島。⚠️ 沒有停車場，沿巷道白線停；第二層瀑布小平台封閉禁止跨越；雨後石階濕滑要穿防滑鞋。",
  },
  {
    name: "龍潭湖風景區",
    city: "礁溪",
    day: 1,
    time: "14:30",
    address: "宜蘭縣礁溪鄉龍潭村環湖路 17 號",
    note: "🌳 環湖步道**全程平坦零陡坡**，繞一圈約 40–50 分鐘。有大碗公溜滑梯與大片草地，免費停車場。排在猴洞坑之後做緩和收尾，剛好不鐵腿。",
  },
  {
    name: "湯圍溝溫泉公園",
    city: "礁溪",
    day: 1,
    time: "19:30",
    address: "宜蘭縣礁溪鄉德陽路 99-11 號",
    note: "♨️ 礁溪市中心的溫泉公園，有**免費半戶外足湯**、付費公共湯屋（湯圍風呂）與溫泉魚 SPA。從品文旅走路約 8 分鐘，飯後散步剛好。旁邊有礁溪幾米兔裝置藝術。Day 3 傍晚上國５前會再來泡一次。",
  },
  {
    name: "礁溪溫泉公園",
    city: "礁溪",
    day: 3,
    time: "09:30",
    address: "宜蘭縣礁溪鄉公園路 16 號",
    note: "🌲 **就在品文旅隔壁**，走路 3 分鐘。園區有森林風呂與步道，Day 3 早餐後散步醒腦用，不用開車。",
  },
  {
    name: "外澳沙灘與伯朗咖啡城堡",
    city: "頭城",
    day: 2,
    time: "09:30",
    address: "宜蘭縣頭城鎮濱海路二段 6 號",
    note: "🌊 正對**龜山島**的沙灘，也是飛行傘起降點。伯朗咖啡城堡在高處可以俯瞰整片海岸線。上午光線好、人也少。",
  },
  {
    name: "蘭陽博物館",
    city: "頭城",
    day: 2,
    time: "10:30",
    address: "宜蘭縣頭城鎮青雲路三段 750 號",
    note: "🎨 烏石港旁的單面山造型建築，宜蘭最具代表性的建築之一，展覽介紹蘭陽平原的山、平原、海三層地景。**週三休館 — 9/19 是週六，正常開放**。館方有收費停車場。也是雨天備案第一順位。",
  },
  {
    name: "頭城老街",
    city: "頭城",
    day: 2,
    time: "12:00",
    address: "宜蘭縣頭城鎮和平街",
    note: "🏮 200 年的商貿老街，閩南建築群保存完整：源合成商號、陳春記商號（1920 年代日治大正年間）、盧纘祥公館（1928 和洋混合式）、頭城十三行（清嘉慶年間十三連棟街屋，現存兩戶）。南北門福德祠形成「街頭街尾土地公」格局，可以摸摸發財龜。",
  },
  {
    name: "羅東觀光夜市",
    city: "羅東",
    day: 2,
    time: "17:45",
    address: "宜蘭縣羅東鎮民權路、公園路、民生路一帶",
    note: "🧋 宜蘭最熱鬧的夜市、全年無休。掃街路線照內內影片的地址走：興東路 → 民生路 → 公園路 → 民權路，一條龍不回頭。⚠️ 週末車位極難找，建議停羅東林業文化園區附近再走過去。",
  },
  {
    name: "潭酵天地觀光工廠",
    city: "礁溪",
    day: 3,
    time: "15:30",
    address: "宜蘭縣礁溪鄉漁復興路三段 250 號",
    note: "🎁 室內觀光工廠，Day 3 下午買伴手禮用，下雨也不影響。導航請確認最新地址。",
  },
  {
    name: "跑馬古道（南段）",
    city: "礁溪",
    day: 1,
    time: "備案",
    address: "宜蘭縣礁溪鄉白石腳路 157 巷 1 號",
    note: "🔁 **備案步道**。山徑寬闊、坡度平緩的碎石路，被稱為「零陡坡」路線。南口與猴洞坑瀑布同一條白石腳路，可以一併安排。全長 5 公里，走一小段折返即可，不必走完。",
  },
];

window.TRIP_DATA = { TRIP, DAYS, CATEGORIES, RESTAURANTS, TRANSPORT, TIPS, SIGHTS };
