// 2026/4 高雄小旅行 — data.js (SSOT)
// Edit this file to update the site. Re-run `npm test` from repo root.

const TRIP = {
  title: "2026/4 高雄小旅行",
  subtitle: "三天兩夜・四人自駕・高雄萬豪",
  heroTitle: "高雄萬豪小度假 × 巨蛋演唱會夜",
  heroDesc: "四人自駕從台北南下，Day 1 晚上順看高雄巨蛋演唱會，隔天悠閒吃透高雄。",
  dates: { start: "2026-04-24", end: "2026-04-26" },
  people: 4,
  country: "TW",
  origin: "台北",
  destinations: ["高雄"],
  hotel: {
    name: "高雄萬豪酒店",
    area: "鼓山・愛河灣",
    address: "高雄市鼓山區中華一路 168 號",
    note: "Check-in 15:00 起 ／ Check-out 12:00 前。4 人建議訂兩間標準房或一間家庭套房。附設地下停車場（房客優惠價，Valet 可用）。抵達後可先寄放行李＋停好車再出門。",
    walking: [
      { to: "輕軌「鼓山區公所」站", minutes: 5 },
      { to: "愛河愛之船碼頭", minutes: 12 },
    ],
  },
  flights: [],
  budget: null,
  extraCards: [
    {
      title: "🎤 4/24 晚演唱會",
      lines: [
        "地點：高雄巨蛋（左營區博愛二路 757 號）",
        "開場：19:30（建議 18:30 前入場）",
        "距飯店：自駕 ~15 分／捷運巨蛋站 R14",
        "巨蛋旁有大型停車場；或 Uber 單趟約 NT$200",
        "帶耳塞、應援小物、行動電源、票券（電子/實體）",
      ],
    },
  ],
};

const DAYS = [
  {
    day: 1,
    date: "2026-04-24",
    dow: "五",
    city: "高雄",
    theme: "自駕南下・入住萬豪・巨蛋演唱會",
    summary: "一早自駕南下，下午 check-in 鹽埕小吃打牙祭，晚上一人赴巨蛋演唱會、其他三人夜遊駁二／棧貳庫。",
    level: "💰💰",
    timeline: [
      { time: "07:00", event: "台北出發（建議走國道3號，車少好開）" },
      { time: "~09:00", event: "西湖服務區（國3 135K）休息＋咖啡、龍鬚糖" },
      { time: "~12:30", event: "抵達高雄萬豪，寄放行李＋停車" },
      { time: "13:00", event: "午餐：鴨肉珍 or 港園牛肉麵（鹽埕老店）" },
      { time: "14:30", event: "鹽埕漫步 ／ 婆婆冰消暑 ／ 巴堂蜂蜜蛋糕順路" },
      { time: "15:00", event: "高雄萬豪正式 check-in、整理行李" },
      { time: "17:00", event: "四人共進早晚餐（建議鹽埕簡餐／汕頭天天沙茶火鍋）" },
      { time: "18:30", event: "🎤 演唱會者 Uber／自駕前往高雄巨蛋（~15 分）" },
      { time: "18:30–21:30", event: "其他三人：駁二、棧貳庫 KW2 海景 ／ 大港橋 ／ 愛河夜景" },
      { time: "19:30", event: "🎤 高雄巨蛋演唱會 開場" },
      { time: "~22:00", event: "演唱會散場 → Uber 回飯店 ／ 或捷運紅線 R14 → R11 轉輕軌" },
      { time: "22:30", event: "四人會合宵夜：六合夜市 or 汕頭泉成（營業到凌晨 1:00）" },
    ],
    meals: [
      { type: "午餐", title: "鴨肉珍 ／ 港園牛肉麵", note: "鹽埕區老店，離飯店近；鴨肉珍週二公休改選港園" },
      { type: "早晚餐", title: "汕頭天天沙茶火鍋", note: "17:00 入座，演唱會者才吃得完；必訂位，週四公休（4/24 週五有開）" },
      { type: "宵夜", title: "六合夜市 ／ 汕頭泉成", note: "演唱會散場後，捷運美麗島站附近；泉成營業到凌晨 1:00" },
    ],
    categories: ["lunch", "dinner", "snack"],
  },
  {
    day: 2,
    date: "2026-04-25",
    dow: "六",
    city: "高雄",
    theme: "壽山動物園・哈瑪星・駁二・瑞豐＋蓮池潭",
    summary: "上午壽山動物園新天空步道，哈瑪星午餐，下午駁二＋大港橋旋轉秀，晚上瑞豐夜市接蓮池潭龍虎塔夜景。",
    level: "💰💰",
    timeline: [
      { time: "07:30", event: "早餐：陳家油飯（建興市場）or 飯店 buffet" },
      { time: "09:00", event: "壽山動物園（離飯店 15 分）— 新天空步道、獼猴友善區" },
      { time: "11:30", event: "下山：哈瑪星代天宮廟口老街" },
      { time: "12:00", event: "午餐：哈瑪星汕頭麵 or 阿財雞絲麵" },
      { time: "13:30", event: "渡船頭海之冰（4 人分一碗巨無霸水果冰剛好）" },
      { time: "14:30", event: "駁二藝術特區 → 14:55 集合大港橋" },
      { time: "15:00", event: "🌉 大港橋水平旋轉秀（每日 15:00 開合）" },
      { time: "15:30", event: "棧貳庫 KW2 小店＋夕陽海景" },
      { time: "16:30", event: "NOW & THEN by nybc 下午茶（駁二 C9-19 倉庫）＋巴堂蜂蜜蛋糕伴手禮" },
      { time: "18:30", event: "開車或捷運到瑞豐夜市（週六有開）" },
      { time: "19:00–21:00", event: "瑞豐夜市：萬國牛排、天使雞排、五哥肉夾饃、文鮮奶麻糬" },
      { time: "21:30", event: "蓮池潭龍虎塔 夜景（2024 重新修復開放，進龍出虎）" },
      { time: "22:30", event: "回飯店泡水池／酒吧小酌" },
    ],
    meals: [
      { type: "早餐", title: "陳家油飯 ／ 高雄萬豪 buffet", note: "陳家油飯 07:00–13:00、週一公休；想吃快出發，賣完就收" },
      { type: "午餐", title: "哈瑪星汕頭麵 ／ 阿財雞絲麵", note: "代天宮廟口 60 年老店；阿財週日公休" },
      { type: "下午茶", title: "NOW & THEN by nybc", note: "駁二倉庫改造，順道買巴堂蜂蜜蛋糕伴手禮" },
      { type: "晚餐", title: "瑞豐夜市 ／ 阿男燒烤", note: "瑞豐夜市：萬國牛排 NT$60 鐵板麵＋無限紅茶濃湯；或鹽埕阿男燒烤（痛風老饕推，烤蛤蠣多汁）。週一、三瑞豐公休" },
    ],
    categories: ["breakfast", "lunch", "cafe", "snack", "dinner"],
  },
  {
    day: 3,
    date: "2026-04-26",
    dow: "日",
    city: "高雄",
    theme: "興隆居早餐・佛光山・大樹鍋貼・北返",
    summary: "早吃興隆居 70 年湯包，上午佛光山佛陀紀念館，中午大樹麵匠巨無霸鍋貼（痛風老饕推薦！），下午啟程北上。",
    level: "💰💰",
    timeline: [
      { time: "07:00", event: "興隆居吃爆漿大湯包＋燒餅（週一公休，4/26 週日有開；早到避排隊）" },
      { time: "08:30", event: "回飯店收行李、Check-out 前泡杯咖啡" },
      { time: "09:30", event: "Check-out ＋ 取車 → 國道10 往大樹方向" },
      { time: "10:15", event: "🪷 佛光山佛陀紀念館（108 米大佛＋八塔一宇，免費入園）" },
      { time: "12:00", event: "大樹麵匠 巨無霸鍋貼 — 痛風老饕推薦！需電話預訂 0986-750355" },
      { time: "13:30", event: "北上出發（走國3，路況較順）" },
      { time: "~15:30", event: "東山服務區（國3 319K）東山鴨頭、銀波布丁買伴手禮" },
      { time: "~17:30", event: "西湖服務區補咖啡、伸展" },
      { time: "~19:00", event: "抵達台北（若不繞大樹，11:00 出發 17:00 可到）" },
    ],
    meals: [
      { type: "早餐", title: "興隆居湯包 ／ 寬來順早餐店", note: "興隆居：凌晨 4 點開到 11:30，7 點前或 10 點後避排；寬來順（與萬豪同在中華一路，車程 10 分）是備選，週一休" },
      { type: "午餐", title: "大樹麵匠 巨無霸鍋貼（備案：舊市羊肉）", note: "痛風老饕推，需電話預訂 0986-750355；訂不到改走國1 到岡山吃舊市羊肉（河華路111號）" },
      { type: "點心", title: "東山鴨頭 ／ 銀波布丁", note: "東山服務區伴手禮必買；滷後炸是招牌作法" },
    ],
    categories: ["breakfast", "lunch", "roadside"],
  },
];

const CATEGORIES = {
  breakfast: { label: "早餐", icon: "🥐" },
  lunch: { label: "午餐", icon: "🍜" },
  dinner: { label: "晚餐", icon: "🍲" },
  snack: { label: "小吃／夜市", icon: "🧋" },
  cafe: { label: "咖啡甜點", icon: "☕" },
  roadside: { label: "沿途／服務區", icon: "🛣️" },
};

const RESTAURANTS = [
  // === 高雄本地 · Day 1 ===
  {
    id: "duck-zhen",
    name: "鴨肉珍",
    city: "高雄",
    category: "lunch",
    area: "鹽埕區",
    address: "高雄市鹽埕區五福四路 258 號",
    days: [1],
    price: "NT$60-150/人",
    must_try: ["鴨肉飯", "下水湯", "鴨腿"],
    note: "65 年老店・2022 米其林必比登。鴨肉切厚塊、帶煙燻香。11:00 前或 14:00 後避峰；週二公休。",
    youtube: [
      { id: "QWQGCAdZ3A8", creator: "厭世甜點店" },
    ],
  },
  {
    id: "gangyuan-beef-noodle",
    name: "港園牛肉麵",
    city: "高雄",
    category: "lunch",
    area: "鹽埕區",
    address: "高雄市鹽埕區大成街 55 號",
    days: [1],
    price: "NT$120-200/人",
    must_try: ["牛肉拌麵", "豬腳拌麵", "牛筋牛肚小菜"],
    note: "60 年老字號，高雄人心中牛肉麵扛霸子。加辣椒＋蒜蓉才是內行。10:30–20:00。",
  },
  {
    id: "tiantian-shacha",
    name: "汕頭天天沙茶火鍋",
    city: "高雄",
    category: "dinner",
    area: "鹽埕區",
    address: "高雄市鹽埕區七賢三路 240 號",
    days: [1],
    price: "NT$400-600/人",
    must_try: ["扁魚湯頭", "溫體牛肉", "爆汁牛肉丸"],
    note: "民國 36 年創立，鹽埕第一家汕頭沙茶。強烈建議訂位；週四公休（4/24 週五有開）。",
  },
  {
    id: "popo-ice",
    name: "高雄婆婆冰創始店",
    city: "高雄",
    category: "snack",
    area: "鹽埕區",
    address: "高雄市鹽埕區七賢三路 135 號 1 樓",
    days: [1],
    price: "NT$80-180/人",
    must_try: ["招牌綜合冰", "超級水果冰", "蜜餞冰"],
    note: "1934 年創立，近百年老店。10:00–23:30，週二公休。捷運鹽埕埔站步行 6 分。",
  },
  {
    id: "liuhe-night-market",
    name: "六合觀光夜市",
    city: "高雄",
    category: "snack",
    area: "新興區",
    address: "高雄市新興區六合二路（近捷運美麗島站）",
    days: [1],
    price: "NT$200-400/人",
    must_try: ["鄭老牌木瓜牛奶", "莊記海產粥", "楊記割包肉圓", "鱔魚姊鱔魚麵"],
    note: "每晚 17:00 起，捷運美麗島站直達。演唱會散場順路殺宵夜最方便。",
  },
  {
    id: "quancheng-shacha",
    name: "汕頭泉成沙茶火鍋（中山總店）",
    city: "高雄",
    category: "dinner",
    area: "新興區",
    address: "高雄市新興區中山橫路 7 號",
    days: [1],
    price: "NT$400-600/人",
    must_try: ["鴛鴦鍋（扁魚＋麻辣）", "溫體牛肉", "自製沙茶醬"],
    note: "80 多年老字號，捷運美麗島站旁，營業到凌晨 1:00。逛完夜市宵夜或演唱會散場都行。",
  },

  // === 高雄本地 · Day 2 ===
  {
    id: "hamasen-shantou",
    name: "哈瑪星汕頭麵（代天宮廟口正老牌）",
    city: "高雄",
    category: "lunch",
    area: "鼓山區",
    address: "高雄市鼓山區鼓波街 27-16 號",
    days: [2],
    price: "NT$40-120/人",
    must_try: ["汕頭乾麵", "餛飩湯", "黑白切"],
    note: "代天宮廟口 60 年，獨門醬汁中藥材＋高粱米酒浸半年。10:00–18:00。",
  },
  {
    id: "acai-noodles",
    name: "阿財雞絲麵",
    city: "高雄",
    category: "lunch",
    area: "鹽埕區",
    address: "高雄市鹽埕區壽星街 11 號",
    days: [2],
    price: "NT$80-200/人",
    must_try: ["手工雞絲麵", "太監雞", "黑白切滷味"],
    note: "50 年老麵店，雞絲麵豬油炸製超彈牙。11:30–21:00，週日公休。",
    youtube: [
      { id: "QWQGCAdZ3A8", creator: "厭世甜點店" },
    ],
  },
  {
    id: "duchuan-ice",
    name: "渡船頭海之冰",
    city: "高雄",
    category: "snack",
    area: "鼓山區",
    address: "高雄市鼓山區濱海一路 76 號",
    days: [2],
    price: "NT$100-300/人",
    must_try: ["巨無霸水果牛奶冰", "雪花冰"],
    note: "輕軌哈瑪星站步行 5 分。4 人分食一碗 20 倍大水果冰剛好。",
  },
  {
    id: "now-then-cafe",
    name: "NOW & THEN by nybc",
    city: "高雄",
    category: "cafe",
    area: "鹽埕區（駁二）",
    address: "高雄市鹽埕區大義街 2-3 號 駁二 C9-19 倉庫",
    days: [2],
    price: "NT$300-500/人",
    must_try: ["招牌早午餐盤", "手沖咖啡", "甜點"],
    note: "駁二大義倉庫內老倉庫改造文青風。週一–五 10:00–17:30、週末 9:00–18:00。",
  },
  {
    id: "zheng-papaya",
    name: "鄭老牌木瓜牛奶",
    city: "高雄",
    category: "snack",
    area: "新興區",
    address: "高雄市新興區六合二路 1 號",
    days: [2],
    price: "NT$60-120/杯",
    must_try: ["木瓜牛奶", "酪梨牛奶", "綜合果汁"],
    note: "1965 年創立，六合夜市入口地標。現點現打無加水，17:00–02:00。",
  },
  {
    id: "ruifeng-night-market",
    name: "瑞豐夜市",
    city: "高雄",
    category: "snack",
    area: "左營區",
    address: "高雄市左營區裕誠路南屏路口（捷運巨蛋站）",
    days: [2],
    price: "NT$250-400/人",
    must_try: ["天使雞排", "五哥肉夾饃", "文鮮奶麻糬", "福中居豆花"],
    note: "比六合更道地的在地夜市。捷運紅線巨蛋站 1 號出口步行 5 分。週一、三公休，4/25 週六有開。",
  },
  {
    id: "hongmaogang-seafood",
    name: "紅毛港海鮮（棧貳庫店）",
    city: "高雄",
    category: "dinner",
    area: "鼓山區（棧貳庫）",
    address: "高雄市鼓山區蓬萊路 17 號 棧貳庫 2 樓",
    days: [2],
    price: "NT$600-1200/人",
    must_try: ["海鮮拼盤", "紅蟳米糕", "現流魚鮮"],
    note: "棧貳庫 KW2 第一排海景，可看大港橋、旗津夕陽。建議訂位。Day 2 若跳過瑞豐可改這裡。",
  },
  {
    id: "batang-cake",
    name: "巴堂蜂蜜蛋糕",
    city: "高雄",
    category: "cafe",
    area: "鹽埕區",
    address: "高雄市鹽埕區新樂街 75 號",
    days: [2],
    price: "NT$200-400/盒",
    must_try: ["蜂蜜蛋糕", "乳酪蛋糕", "蜂蜜生乳捲"],
    note: "鹽埕近 50 年老糕餅店，適合買回台北當伴手禮。新鮮蜂蜜蛋糕綿密濕潤。",
  },

  // === 高雄本地 · Day 2 追加（含痛風老饕推薦） ===
  {
    id: "chen-family-oil-rice",
    name: "陳家油飯",
    city: "高雄",
    category: "breakfast",
    area: "三民區（建興市場）",
    address: "高雄市三民區建興路 281 號",
    days: [2],
    price: "NT$50-120/人",
    must_try: ["古早味油飯", "醬滷雞腿", "香菇肉羹"],
    note: "建興市場老字號，米粒彈牙＋南部甜香菇肉羹。07:00–13:00，賣完就收；週一公休。",
  },
  {
    id: "laochiang-tea",
    name: "老江紅茶牛奶（七賢總店）",
    city: "高雄",
    category: "snack",
    area: "新興區",
    address: "高雄市新興區南台橫路 19 號",
    days: [1, 2],
    price: "NT$60-120/人",
    must_try: ["招牌紅茶牛奶", "起酥蛋吐司", "肉鬆蛋吐司"],
    note: "1953 年創立 70 年老店，24 小時營業。演唱會散場宵夜、隔日清晨早餐都可；痛風老饕 IG 關聯店家。",
  },
  {
    id: "wanguo-steak",
    name: "萬國牛排（瑞豐店）",
    city: "高雄",
    category: "dinner",
    area: "左營區（瑞豐夜市）",
    address: "高雄市左營區裕誠路 1128 號",
    days: [2],
    price: "NT$100-250/人",
    must_try: ["NT$60 鐵板麵", "雞腿排", "無限濃湯＋紅茶"],
    note: "瑞豐夜市傳奇 $60 鐵板麵，一天破千份。17:00–01:00；排 30 分起跳。",
  },

  // === 高雄本地 · Day 3 ===
  {
    id: "xinglongju",
    name: "興隆居",
    city: "高雄",
    category: "breakfast",
    area: "前金區",
    address: "高雄市前金區六合二路 186 號",
    days: [3],
    price: "NT$50-120/人",
    must_try: ["爆漿大湯包", "事事如意燒餅（全加料）", "蛋餅"],
    note: "1954 年老店，凌晨 4 點–11:30。排隊常到大馬路，7 點前到或 10 點後最鬆；週一公休（4/26 週日有開）。",
  },
  {
    id: "dashu-dumpling",
    name: "大樹麵匠（巨無霸鍋貼）",
    city: "高雄",
    category: "lunch",
    area: "大樹區",
    address: "高雄市大樹區中興西路 27 號",
    days: [3],
    price: "NT$80-150/人",
    must_try: ["手工巨無霸鍋貼（NT$7.5/顆）", "水煎包", "韭菜盒"],
    note: "皮薄餡多、肉汁爆發。**需預訂 0986-750355**，佛光山下來順路。12:00–18:30。",
    youtube: [
      { id: "3QK6nFhTpoo", time: "10:17", creator: "痛風老饕" },
    ],
  },
  {
    id: "jiushi-lamb",
    name: "舊市羊肉",
    city: "高雄",
    category: "lunch",
    area: "岡山區",
    address: "高雄市岡山區河華路 111 號",
    days: [3],
    price: "NT$200-500/人",
    must_try: ["當歸羊肉湯", "沙茶羊肉", "三杯羊排"],
    note: "岡山羊肉老字號；若大樹麵匠沒訂到，改走國1 到岡山吃這家。",
    youtube: [
      { id: "3QK6nFhTpoo", creator: "痛風老饕" },
    ],
  },
  {
    id: "fengshan-xu-milkfish",
    name: "鳳山徐家𩼣魚湯",
    city: "高雄",
    category: "breakfast",
    area: "鳳山區",
    address: "高雄市鳳山區中山路 106-1 號",
    days: [3],
    price: "NT$80-200/人",
    must_try: ["𩼣魚湯", "虱目魚肚湯", "魚皮湯", "滷肉飯"],
    note: "早餐到中午的老店款；若走國1 南下北返可順繞。",
    youtube: [
      { id: "3QK6nFhTpoo", creator: "痛風老饕" },
    ],
  },
  {
    id: "jueue-noodle",
    name: "堀江麵",
    city: "高雄",
    category: "lunch",
    area: "鹽埕區",
    address: "高雄市鹽埕區必忠街 223 號",
    days: [2],
    price: "NT$80-150/人",
    must_try: ["招牌堀江乾麵", "餛飩湯", "滷味"],
    note: "兩支痛風老饕影片都推（「排兩小時」與「老饕 brunch」）。10:00–14:00 午餐限定，週一休。",
    youtube: [
      { id: "APLGAgNhCJA", creator: "痛風老饕" },
      { id: "jOjSo6QpE60", creator: "痛風老饕" },
    ],
  },
  {
    id: "qinjie-fish-porridge",
    name: "琴姐土魠魚粥香菇肉燥飯",
    city: "高雄",
    category: "breakfast",
    area: "鹽埕區",
    address: "高雄市鹽埕區北斗街 28 號",
    days: [2],
    price: "NT$80-180/人",
    must_try: ["土魠魚粥", "香菇肉燥飯"],
    note: "「排兩小時值不值得」首選之一。鹽埕老味道。",
    youtube: [
      { id: "APLGAgNhCJA", creator: "痛風老饕" },
    ],
  },
  {
    id: "kuanlaishun-breakfast",
    name: "寬來順早餐店",
    city: "高雄",
    category: "breakfast",
    area: "左營區",
    address: "高雄市左營區中華一路 5-14 號",
    days: [3],
    price: "NT$50-120/人",
    must_try: ["燒餅", "豆漿", "蛋餅"],
    note: "04:00–12:00，週一休。**與萬豪同在中華一路**，開車 10 分鐘，Day 3 避開興隆居排隊的好選擇。",
    youtube: [
      { id: "jOjSo6QpE60", creator: "痛風老饕" },
    ],
  },
  {
    id: "aman-bbq",
    name: "阿男燒烤",
    city: "高雄",
    category: "dinner",
    area: "鹽埕區",
    address: "高雄市鹽埕區新樂街 229-1 號",
    days: [2],
    price: "NT$300-600/人",
    must_try: ["烤蛤蠣", "烤肉串", "烤魚"],
    note: "晚上才出現的白蝙蝠老闆（網友暱稱）；蛤蠣多汁爆出名。",
    youtube: [
      { id: "3QK6nFhTpoo", creator: "痛風老饕" },
    ],
  },
  {
    id: "jibo-shaojiu-chicken",
    name: "雞伯燒酒雞",
    city: "高雄",
    category: "dinner",
    area: "新興區",
    address: "高雄市新興區八德二路 76-1 號",
    days: [1],
    price: "NT$300-500/人",
    must_try: ["燒酒雞湯", "麻油雞", "雞腿飯"],
    note: "原本是 30 年前酒店外送菜，在地老饕指名；演唱會散場的宵夜選項之一。",
    youtube: [
      { id: "APLGAgNhCJA", creator: "痛風老饕" },
    ],
  },

  // === 自強夜市 攤商（痛風老饕 aJ_eDHjvW7I「高流演唱會必吃」）===
  {
    id: "laopai-baitangguo",
    name: "老牌白糖粿（自強夜市）",
    city: "高雄",
    category: "snack",
    area: "前金區（自強夜市）",
    address: "高雄市前金區自強夜市（自強二路／三路）",
    days: [1, 2],
    price: "NT$30-80/人",
    must_try: ["白糖粿（花生）", "白糖粿（芝麻）"],
    note: "爆排白糖粿兩大流派之一；建議與「正牌白糖粿」各買一份比較。",
    youtube: [
      { id: "aJ_eDHjvW7I", time: "01:20", creator: "痛風老饕" },
    ],
  },
  {
    id: "zhengpai-baitangguo",
    name: "正牌白糖粿（自強夜市）",
    city: "高雄",
    category: "snack",
    area: "前金區（自強夜市）",
    address: "高雄市前金區自強夜市",
    days: [1, 2],
    price: "NT$30-80/人",
    must_try: ["白糖粿", "地瓜球"],
    note: "與「老牌」對打的另一家。",
    youtube: [
      { id: "aJ_eDHjvW7I", time: "20:13", creator: "痛風老饕" },
    ],
  },
  {
    id: "nanfeng-rice",
    name: "南豐魯肉飯（自強夜市）",
    city: "高雄",
    category: "snack",
    area: "前金區（自強夜市）",
    address: "高雄市前金區自強夜市",
    days: [1, 2],
    price: "NT$40-100/人",
    must_try: ["大塊霸氣滷肉飯", "滷蛋", "油豆腐"],
    note: "大塊肉而非肉燥，份量霸氣。",
    youtube: [
      { id: "aJ_eDHjvW7I", time: "03:42", creator: "痛風老饕" },
    ],
  },
  {
    id: "chunri-tofu",
    name: "春日蒜香豆干（自強夜市）",
    city: "高雄",
    category: "snack",
    area: "前金區（自強夜市）",
    address: "高雄市前金區自強夜市",
    days: [1, 2],
    price: "NT$40-80/人",
    must_try: ["蒜味滷豆干", "滷味拼盤"],
    note: "蒜味濃郁。",
    youtube: [
      { id: "aJ_eDHjvW7I", time: "07:08", creator: "痛風老饕" },
    ],
  },
  {
    id: "yujia-dumpling",
    name: "于家水餃大王（自強夜市）",
    city: "高雄",
    category: "snack",
    area: "前金區（自強夜市）",
    address: "高雄市前金區自強夜市",
    days: [1, 2],
    price: "NT$60-150/人",
    must_try: ["手工水餃", "酸辣湯"],
    note: "痛風老饕推薦",
    youtube: [
      { id: "aJ_eDHjvW7I", time: "10:27", creator: "痛風老饕" },
    ],
  },
  {
    id: "zhenxiang-tea",
    name: "蓁香茗茶（自強夜市）",
    city: "高雄",
    category: "snack",
    area: "前金區（自強夜市）",
    address: "高雄市前金區自強夜市",
    days: [1, 2],
    price: "NT$0-60/人",
    must_try: ["免費紅茶", "免費豆漿", "茶葉蛋"],
    note: "**免費紅茶豆漿喝到飽**是全夜市傳奇。",
    youtube: [
      { id: "aJ_eDHjvW7I", time: "12:30", creator: "痛風老饕" },
    ],
  },
  {
    id: "houdefu-tangbao",
    name: "厚得福湯包麵食專賣店（自強夜市）",
    city: "高雄",
    category: "snack",
    area: "前金區（自強夜市）",
    address: "高雄市前金區自強夜市",
    days: [1, 2],
    price: "NT$80-180/人",
    must_try: ["湯包", "紅油抄手", "擔擔麵"],
    note: "痛風老饕推薦",
    youtube: [
      { id: "aJ_eDHjvW7I", time: "15:18", creator: "痛風老饕" },
      { id: "4oL6YTda5kw", time: "08:11", creator: "那個女生 Kiki" },
    ],
  },
  {
    id: "hushuo-tofu",
    name: "胡說八道酵素臭豆腐（自強夜市）",
    city: "高雄",
    category: "snack",
    area: "前金區（自強夜市）",
    address: "高雄市前金區自強夜市",
    days: [1, 2],
    price: "NT$60-120/人",
    must_try: ["酵素臭豆腐", "泡菜"],
    note: "酵素發酵，風味獨特。",
    youtube: [
      { id: "aJ_eDHjvW7I", time: "17:45", creator: "痛風老饕" },
    ],
  },
  {
    id: "aliang-chicken",
    name: "阿亮香雞排（自強夜市）",
    city: "高雄",
    category: "snack",
    area: "前金區（自強夜市）",
    address: "高雄市前金區自強夜市",
    days: [1, 2],
    price: "NT$60-120/人",
    must_try: ["香雞排", "甜不辣"],
    note: "痛風老饕推薦",
    youtube: [
      { id: "aJ_eDHjvW7I", time: "21:39", creator: "痛風老饕" },
    ],
  },

  // === 瑞豐夜市 其他攤商（痛風老饕 SvYPdB4-JU8 口袋名單）===
  {
    id: "xinchuan-tea",
    name: "鑫川鴛鴦奶茶（瑞豐夜市）",
    city: "高雄",
    category: "snack",
    area: "左營區（瑞豐夜市）",
    address: "高雄市左營區瑞豐夜市",
    days: [2],
    price: "NT$40-80/杯",
    must_try: ["鴛鴦奶茶", "紅茶拿鐵"],
    note: "瑞豐傳統飲料攤。",
    youtube: [
      { id: "SvYPdB4-JU8", creator: "痛風老饕" },
    ],
  },
  {
    id: "aphan-qq-egg",
    name: "阿椪的店 QQ 蛋（瑞豐夜市）",
    city: "高雄",
    category: "snack",
    area: "左營區（瑞豐夜市）",
    address: "高雄市左營區瑞豐夜市",
    days: [2],
    price: "NT$40-80/人",
    must_try: ["QQ 蛋（雞蛋糕）", "鯛魚燒"],
    note: "小孩子最愛的彈牙雞蛋糕。",
    youtube: [
      { id: "SvYPdB4-JU8", creator: "痛風老饕" },
    ],
  },
  {
    id: "zeng-fujian-noodle",
    name: "曾氏福建炒麵（瑞豐夜市）",
    city: "高雄",
    category: "snack",
    area: "左營區（瑞豐夜市）",
    address: "高雄市左營區瑞豐夜市",
    days: [2],
    price: "NT$60-120/人",
    must_try: ["福建炒麵", "炒米粉"],
    note: "痛風老饕推薦",
    youtube: [
      { id: "SvYPdB4-JU8", creator: "痛風老饕" },
    ],
  },
  {
    id: "okinawa-squid",
    name: "沖繩酥炸大魷魚（瑞豐夜市）",
    city: "高雄",
    category: "snack",
    area: "左營區（瑞豐夜市）",
    address: "高雄市左營區瑞豐夜市",
    days: [2],
    price: "NT$80-150/人",
    must_try: ["酥炸大魷魚", "胡椒蝦"],
    note: "痛風老饕推薦",
    youtube: [
      { id: "SvYPdB4-JU8", creator: "痛風老饕" },
    ],
  },
  {
    id: "liujiazhuang-papaya",
    name: "劉家莊木瓜牛乳大王（瑞豐夜市）",
    city: "高雄",
    category: "snack",
    area: "左營區（瑞豐夜市）",
    address: "高雄市左營區瑞豐夜市",
    days: [2],
    price: "NT$60-100/杯",
    must_try: ["木瓜牛奶", "香蕉牛奶"],
    note: "瑞豐夜市的木瓜牛奶招牌。",
    youtube: [
      { id: "SvYPdB4-JU8", creator: "痛風老饕" },
    ],
  },
  {
    id: "pengshi-stinky-tofu",
    name: "彭氏臭豆腐（瑞豐夜市）",
    city: "高雄",
    category: "snack",
    area: "左營區（瑞豐夜市）",
    address: "高雄市左營區瑞豐夜市",
    days: [2],
    price: "NT$60-120/人",
    must_try: ["臭豆腐", "泡菜"],
    note: "**僅週二、六有開**（4/25 週六有開！）。",
    youtube: [
      { id: "SvYPdB4-JU8", creator: "痛風老饕" },
    ],
  },

  // === 鹽埕／前金區 其他老店（痛風老饕 3QK6nFhTpoo / APLGAgNhCJA）===
  {
    id: "dayi-wuming-noodle",
    name: "大義街無名麵店",
    city: "高雄",
    category: "lunch",
    area: "鹽埕區",
    address: "高雄市鹽埕區大義街 64 號",
    days: [1, 2],
    price: "NT$60-120/人",
    must_try: ["乾麵", "餛飩湯", "黑白切"],
    note: "無招牌的在地老店。",
    youtube: [
      { id: "3QK6nFhTpoo", time: "01:05", creator: "痛風老饕" },
    ],
  },
  {
    id: "mazu-scallion-pancake",
    name: "馬祖蔥油餅",
    city: "高雄",
    category: "breakfast",
    area: "前金區",
    address: "高雄市前金區自強二路 154 號",
    days: [1, 2],
    price: "NT$40-80/人",
    must_try: ["蔥油餅加蛋", "韭菜盒"],
    note: "痛風老饕推薦",
    youtube: [
      { id: "3QK6nFhTpoo", time: "04:28", creator: "痛風老饕" },
    ],
  },
  {
    id: "xiangsihai-fish-cake",
    name: "香四海旗魚黑輪",
    city: "高雄",
    category: "snack",
    area: "前金區",
    address: "高雄市前金區前金第一公有市場",
    days: [1, 2],
    price: "NT$40-100/人",
    must_try: ["旗魚黑輪", "甜不辣"],
    note: "前金第一公有市場內。",
    youtube: [
      { id: "3QK6nFhTpoo", time: "06:10", creator: "痛風老饕" },
    ],
  },
  {
    id: "wuming-scallion-leek",
    name: "無名蔥油餅與韭菜盒",
    city: "高雄",
    category: "breakfast",
    area: "鹽埕區",
    address: "高雄市鹽埕區必忠街 98 號",
    days: [2],
    price: "NT$40-80/人",
    must_try: ["蔥油餅", "韭菜盒子"],
    note: "鹽埕必忠街老店。",
    youtube: [
      { id: "APLGAgNhCJA", time: "17:44", creator: "痛風老饕" },
    ],
  },
  {
    id: "xiayiguo-bun",
    name: "下一鍋水煎包",
    city: "高雄",
    category: "breakfast",
    area: "鹽埕區",
    address: "高雄市鹽埕區大禮街 24 號",
    days: [2],
    price: "NT$30-80/人",
    must_try: ["水煎包", "豬肉餡餅", "韭菜盒子"],
    note: "& 22:44（兩度入鏡）。",
    youtube: [
      { id: "APLGAgNhCJA", time: "20:28", creator: "痛風老饕" },
      { id: "QWQGCAdZ3A8", creator: "厭世甜點店" },
    ],
  },
  {
    id: "bianzui-smoked-goose",
    name: "扁嘴之家燻茶鵝",
    city: "高雄",
    category: "dinner",
    area: "鹽埕區",
    address: "高雄市鹽埕區大禮街 24 號",
    days: [1, 2],
    price: "NT$200-500/人",
    must_try: ["燻茶鵝", "鵝油拌飯"],
    note: "與下一鍋水煎包同址。",
    youtube: [
      { id: "APLGAgNhCJA", time: "20:23", creator: "痛風老饕" },
    ],
  },
  {
    id: "guangyuan-pancake",
    name: "光遠鬆餅坊",
    city: "高雄",
    category: "cafe",
    area: "前金區",
    address: "高雄市前金區自強三路 245 號",
    days: [2],
    price: "NT$80-180/人",
    must_try: ["古早味鬆餅", "酥脆小黃瓜"],
    note: "鬆餅＋小黃瓜是招牌組合。",
    youtube: [
      { id: "3QK6nFhTpoo", time: "20:26", creator: "痛風老饕" },
    ],
  },

  // === 老饕 Brunch 系列（痛風老饕 jOjSo6QpE60）===
  {
    id: "fanziming-soup",
    name: "番仔明古早味雜菜",
    city: "高雄",
    category: "breakfast",
    area: "三民區",
    address: "高雄市三民區自立一路 429 號",
    days: [2, 3],
    price: "NT$60-150/人",
    must_try: ["古早味雜菜湯", "滷肉飯"],
    note: "07:15–12:40，週三休；4/25 週六、4/26 週日都有開。",
    youtube: [
      { id: "jOjSo6QpE60", time: "00:41", creator: "痛風老饕" },
    ],
  },
  {
    id: "fuxing-meatball",
    name: "復興肉圓",
    city: "高雄",
    category: "lunch",
    area: "新興區",
    address: "高雄市新興區復興一路 131 號",
    days: [2],
    price: "NT$40-100/人",
    must_try: ["蒸肉圓（Q 皮）", "香菇肉羹湯"],
    note: "11:00–17:00，週日休。南部蒸派肉圓代表。",
    youtube: [
      { id: "jOjSo6QpE60", time: "03:11", creator: "痛風老饕" },
    ],
  },
  {
    id: "fangde-pork-noodle",
    name: "古早味碳火芳德豬肉冬粉",
    city: "高雄",
    category: "lunch",
    area: "新興區",
    address: "高雄市新興區大同一路 100 號",
    days: [2],
    price: "NT$60-150/人",
    must_try: ["碳火豬肉冬粉", "滷菜"],
    note: "10:30–18:30（15:00–16:30 午休），週日休。",
    youtube: [
      { id: "jOjSo6QpE60", time: "05:51", creator: "痛風老饕" },
    ],
  },
  {
    id: "yarou-he",
    name: "鴨肉和",
    city: "高雄",
    category: "lunch",
    area: "三民區",
    address: "高雄市三民區建國三路 395-1 號",
    days: [1, 2],
    price: "NT$100-200/人",
    must_try: ["鴨肉飯", "下水湯"],
    note: "10:00–21:00，週一休。鴨肉珍的三民區對手。",
    youtube: [
      { id: "jOjSo6QpE60", time: "06:22", creator: "痛風老饕" },
    ],
  },
  {
    id: "yunjia-lemon",
    name: "雲家檸檬大王",
    city: "高雄",
    category: "snack",
    area: "三民區（三民市場）",
    address: "高雄市三民區自強一路 226 號",
    days: [1, 2],
    price: "NT$40-80/杯",
    must_try: ["招牌檸檬汁", "綜合果汁"],
    note: "09:00–22:00。三民市場內。",
    youtube: [
      { id: "jOjSo6QpE60", time: "09:27", creator: "痛風老饕" },
    ],
  },
  {
    id: "xiaodao-apartment",
    name: "小島公寓",
    city: "高雄",
    category: "cafe",
    area: "新興區",
    address: "高雄市新興區六合一路 148 號",
    days: [2],
    price: "NT$200-400/人",
    must_try: ["早午餐盤", "手沖咖啡"],
    note: "六合一路文青咖啡店。",
    youtube: [
      { id: "jOjSo6QpE60", time: "11:44", creator: "痛風老饕" },
    ],
  },
  {
    id: "dengjia-tangyuan",
    name: "鄧家粉圓",
    city: "高雄",
    category: "snack",
    area: "三民區",
    address: "高雄市三民區立德街 1 巷 2 號",
    days: [1, 2],
    price: "NT$40-80/人",
    must_try: ["手工粉圓冰", "仙草凍"],
    note: "10:00–21:45。",
    youtube: [
      { id: "jOjSo6QpE60", time: "17:39", creator: "痛風老饕" },
    ],
  },

  // === 其他候選 ===
  {
    id: "jiayuxian-seafood",
    name: "家遇鮮海鮮鍋燒（吉林店）",
    city: "高雄",
    category: "lunch",
    area: "三民區",
    address: "高雄市三民區吉林街",
    days: [2],
    price: "NT$180-300/人",
    must_try: ["海鮮鍋燒麵（蝦、干貝、蛤蠣）", "痛風系列"],
    note: "網路推為「痛風鍋燒麵海味擔當」；店名「痛風」與痛風老饕頻道同調，有可能是她流量帶起的店。",
  },

  {
    id: "laopai-pig-blood",
    name: "老牌豬血湯",
    city: "高雄",
    category: "breakfast",
    area: "三民區",
    address: "高雄市三民區建國三路 272 號",
    days: [2],
    price: "NT$60-150/人",
    must_try: ["豬血湯", "豬雜湯", "肉燥飯"],
    note: "厭世甜點店拿拿摳口袋名單。三民區老字號豬血湯。",
    youtube: [
      { id: "QWQGCAdZ3A8", creator: "厭世甜點店" },
    ],
  },

  {
    id: "tianchi-wintermelon",
    name: "天池冬瓜茶",
    city: "高雄",
    category: "snack",
    area: "鹽埕區",
    address: "高雄市鹽埕區新樂街 113 號",
    days: [1, 2],
    price: "NT$30-60/杯",
    must_try: ["冬瓜茶", "冬瓜檸檬"],
    note: "厭世甜點店拿拿摳推薦。鹽埕冬瓜茶老店。",
    youtube: [
      { id: "QWQGCAdZ3A8", creator: "厭世甜點店" },
    ],
  },

  {
    id: "migao-city",
    name: "米糕城",
    city: "高雄",
    category: "lunch",
    area: "鹽埕區",
    address: "高雄市鹽埕區大仁路 107 號",
    days: [1, 2],
    price: "NT$60-120/人",
    must_try: ["筒仔米糕", "四神湯", "肉羹"],
    note: "厭世甜點店拿拿摳口袋。鹽埕老店米糕。",
    youtube: [
      { id: "QWQGCAdZ3A8", creator: "厭世甜點店" },
    ],
  },

  {
    id: "aloha-luwei",
    name: "阿囉哈滷味",
    city: "高雄",
    category: "snack",
    area: "鹽埕區",
    address: "高雄市鹽埕區大仁路 154 號",
    days: [1, 2],
    price: "NT$100-250/人",
    must_try: ["招牌滷味拼盤", "滷鴨翅", "滷豆乾"],
    note: "厭世甜點店拿拿摳口袋。鹽埕滷味老店。",
    youtube: [
      { id: "QWQGCAdZ3A8", creator: "厭世甜點店" },
    ],
  },

  {
    id: "beigang-tongzi-migao",
    name: "高雄北港蔡筒仔米糕",
    city: "高雄",
    category: "lunch",
    area: "鹽埕區",
    address: "高雄市鹽埕區河西路 167 號",
    days: [1, 2],
    price: "NT$60-120/人",
    must_try: ["筒仔米糕", "魚丸湯"],
    note: "厭世甜點店拿拿摳推薦。鹽埕河西路筒仔米糕。",
    youtube: [
      { id: "QWQGCAdZ3A8", creator: "厭世甜點店" },
    ],
  },

  {
    id: "hamasen-black-fishball",
    name: "哈瑪星黑旗魚丸大王",
    city: "高雄",
    category: "lunch",
    area: "鼓山區",
    address: "高雄市鼓山區鼓波街 27-7 號",
    days: [2],
    price: "NT$60-120/人",
    must_try: ["黑旗魚丸湯", "米糕"],
    note: "厭世甜點店拿拿摳推薦。與哈瑪星汕頭麵同鼓波街，可順吃。",
    youtube: [
      { id: "QWQGCAdZ3A8", creator: "厭世甜點店" },
    ],
  },

  {
    id: "qishan-pigheart-noodle",
    name: "旗山秀明豬心冬粉",
    city: "高雄",
    category: "lunch",
    area: "旗山區",
    address: "高雄市旗山區永平街 41 號",
    days: [3],
    price: "NT$100-200/人",
    must_try: ["豬心冬粉", "豬肝湯", "豬腰湯"],
    note: "2024 米其林必比登新增。旗山老街附近，Day 3 若改走旗山／美濃路線可順吃。",
    youtube: [
      { id: "vqpvRxxEApQ", creator: "厭世甜點店" },
    ],
  },

  {
    id: "chunlan-gua-bao",
    name: "春蘭割包",
    city: "高雄",
    category: "lunch",
    area: "新興區",
    address: "高雄市新興區復興一路 5 號",
    days: [2],
    price: "NT$60-150/人",
    must_try: ["爆漿割包", "四神湯"],
    note: "2024 米其林必比登。新興區人氣排隊割包。",
    youtube: [
      { id: "vqpvRxxEApQ", creator: "厭世甜點店" },
    ],
  },

  {
    id: "maiyanshun-taiwanese",
    name: "賣塩順台菜（正宗台菜）",
    city: "高雄",
    category: "dinner",
    area: "鼓山區",
    address: "高雄市鼓山區青海路 173 號",
    days: [2],
    price: "NT$400-800/人",
    must_try: ["剝皮辣椒雞湯", "老薑炒雞腿", "古早味家常菜"],
    note: "2024 米其林必比登新增。剝皮辣椒雞湯是招牌。",
    youtube: [
      { id: "vqpvRxxEApQ", creator: "厭世甜點店" },
    ],
  },

  {
    id: "xiaodun-kitchen",
    name: "小燉食室",
    city: "高雄",
    category: "dinner",
    area: "前鎮區",
    address: "高雄市前鎮區廣西路 226 號",
    days: [2],
    price: "NT$300-600/人",
    must_try: ["滷豬腳", "燉品", "白飯"],
    note: "2024 米其林必比登新增。前鎮區家常燉菜。",
    youtube: [
      { id: "vqpvRxxEApQ", creator: "厭世甜點店" },
    ],
  },

  {
    id: "liangjia-pigfoot",
    name: "良佳豬腳",
    city: "高雄",
    category: "lunch",
    area: "三民區",
    address: "高雄市三民區陽明路 229 號",
    days: [2],
    price: "NT$200-400/人",
    must_try: ["滷豬腳", "豬腳飯", "苦瓜排骨湯"],
    note: "2024 米其林必比登新增。三民區滷豬腳老店。",
    youtube: [
      { id: "vqpvRxxEApQ", creator: "厭世甜點店" },
    ],
  },

  {
    id: "xianzuo-riceball",
    name: "現做越光米飯團（新潟觀光物產）",
    city: "高雄",
    category: "breakfast",
    area: "鼓山區",
    address: "高雄市鼓山區青海路 63 號",
    days: [2],
    price: "NT$60-150/人",
    must_try: ["越光米飯團", "味噌湯"],
    note: "厭世甜點店 × 住高雄日本人 Mana。現做日式飯糰。",
    youtube: [
      { id: "GWTY0pTp3Jc", creator: "厭世甜點店" },
    ],
  },

  {
    id: "xiaquan-kai",
    name: "夏全開",
    city: "高雄",
    category: "dinner",
    area: "左營區",
    address: "高雄市左營區翠峰路 26 號",
    days: [2],
    price: "NT$400-800/人",
    must_try: ["名古屋料理", "味噌豬排"],
    note: "厭世甜點店 × Mana 推薦。道地名古屋料理。",
    youtube: [
      { id: "GWTY0pTp3Jc", creator: "厭世甜點店" },
    ],
  },

  {
    id: "jintianjia-ramen",
    name: "金田家拉麵",
    city: "高雄",
    category: "lunch",
    area: "左營區",
    address: "高雄市左營區安吉街 380 號",
    days: [2],
    price: "NT$250-400/人",
    must_try: ["豚骨拉麵", "沾麵"],
    note: "厭世甜點店 × Mana「最好吃的拉麵」。左營日式拉麵。",
    youtube: [
      { id: "GWTY0pTp3Jc", creator: "厭世甜點店" },
    ],
  },

  {
    id: "canxiong-puff",
    name: "倉熊手作甜品（招牌泡芙）",
    city: "高雄",
    category: "cafe",
    area: "左營區",
    address: "高雄市左營區德威街 54 號",
    days: [2],
    price: "NT$60-180/人",
    must_try: ["脆皮泡芙", "招牌達克瓦茲"],
    note: "厭世甜點店 × Mana 推薦脆皮泡芙。",
    youtube: [
      { id: "GWTY0pTp3Jc", creator: "厭世甜點店" },
    ],
  },

  {
    id: "chaolai-izakaya",
    name: "潮來居酒屋",
    city: "高雄",
    category: "dinner",
    area: "前金區",
    address: "高雄市前金區文武二街 107 號",
    days: [1, 2],
    price: "NT$500-1000/人",
    must_try: ["日式串燒", "生魚片", "清酒"],
    note: "厭世甜點店 × Mana 推薦。前金區日式居酒屋。",
    youtube: [
      { id: "GWTY0pTp3Jc", creator: "厭世甜點店" },
    ],
  },

  {
    id: "houshan-dacquoise",
    name: "厚山 Hòu Shān 達克瓦茲",
    city: "高雄",
    category: "cafe",
    area: "三民區",
    address: "高雄市三民區中華二路 337 號",
    days: [2],
    price: "NT$60-180/人",
    must_try: ["榴槤達克瓦茲", "經典達克瓦茲"],
    note: "厭世甜點店 × Mana 推薦。三民區達克瓦茲專賣。",
    youtube: [
      { id: "GWTY0pTp3Jc", creator: "厭世甜點店" },
    ],
  },

  {
    id: "yancheng-tea",
    name: "鹽埕茶町",
    city: "高雄",
    category: "cafe",
    area: "鹽埕區",
    address: "高雄市鹽埕區瀨南街 35 號",
    days: [2],
    price: "NT$100-250/人",
    must_try: ["抹抹茶冰", "抹茶拿鐵"],
    note: "厭世甜點店「地表最抹抹茶冰」。鹽埕抹茶冰專賣。",
    youtube: [
      { id: "yFfeElqwKbw", creator: "厭世甜點店" },
    ],
  },

  {
    id: "heyuan-cane-ice",
    name: "禾苑蔗片冰",
    city: "高雄",
    category: "snack",
    area: "鼓山區",
    address: "高雄市鼓山區博愛二路 347 號",
    days: [2],
    price: "NT$80-180/人",
    must_try: ["炭燒蔗片冰", "黑糖剉冰"],
    note: "厭世甜點店推薦冰品。**近高雄巨蛋（博愛二路）**，4/24 演唱會前後可順吃。",
    youtube: [
      { id: "yFfeElqwKbw", creator: "厭世甜點店" },
    ],
  },

  {
    id: "yeyuetang-snow",
    name: "葉月堂手作雪花冰（富民店）",
    city: "高雄",
    category: "snack",
    area: "左營區",
    address: "高雄市左營區富民路 18 號",
    days: [2],
    price: "NT$120-250/人",
    must_try: ["酪梨雪花冰", "芒果雪花冰"],
    note: "厭世甜點店推薦。左營手作雪花冰。",
    youtube: [
      { id: "yFfeElqwKbw", creator: "厭世甜點店" },
    ],
  },

  {
    id: "kongqi-icecream",
    name: "空氣分子霜淇淋",
    city: "高雄",
    category: "snack",
    area: "三民區",
    address: "高雄市三民區灣中街 66 號",
    days: [2],
    price: "NT$80-160/人",
    must_try: ["繡球花霜淇淋", "季節霜淇淋"],
    note: "厭世甜點店推薦。繡球花造型霜淇淋是招牌。",
    youtube: [
      { id: "yFfeElqwKbw", creator: "厭世甜點店" },
    ],
  },

  {
    id: "guanyu-sweet",
    name: "關愉甜",
    city: "高雄",
    category: "cafe",
    area: "三民區",
    address: "高雄市三民區大昌二路 549 號",
    days: [2],
    price: "NT$150-300/人",
    must_try: ["季節甜點", "手沖咖啡"],
    note: "厭世甜點店推薦。三民區質感甜點店。",
    youtube: [
      { id: "yFfeElqwKbw", creator: "厭世甜點店" },
    ],
  },

  {
    id: "yuqian-tea",
    name: "御前上茶（漢神成功店）",
    city: "高雄",
    category: "cafe",
    area: "苓雅區",
    address: "高雄市苓雅區成功一路 266 號",
    days: [2],
    price: "NT$100-200/杯",
    must_try: ["鐵觀音拿鐵", "珍珠奶茶"],
    note: "Kiki 內行人才知 #13 推薦。漢神成功店下午茶。",
    youtube: [
      { id: "kHRMiFz4JdI", time: "11:25", creator: "那個女生 Kiki" },
    ],
  },

  {
    id: "yizhi-beef-katsu",
    name: "逸之牛 牛かつ·焼肉専売（高雄本家）",
    city: "高雄",
    category: "dinner",
    area: "新興區",
    address: "高雄市新興區中山橫路 5 號",
    days: [2],
    price: "NT$500-1000/人",
    must_try: ["爆汁炸牛排", "日式燒肉"],
    note: "Kiki 內行人才知 #13 推薦。日式炸牛排專門。",
    youtube: [
      { id: "kHRMiFz4JdI", time: "13:11", creator: "那個女生 Kiki" },
    ],
  },

  {
    id: "bingta-snow",
    name: "冰塔職人雪花（文化店）",
    city: "高雄",
    category: "snack",
    area: "新興區",
    address: "高雄市新興區文化路 64 號",
    days: [2],
    price: "NT$100-220/人",
    must_try: ["雪花冰", "炸餡芋泥三明治"],
    note: "Kiki 吃爆十家 #24 推薦。新興區文化路雪花冰。",
    youtube: [
      { id: "4oL6YTda5kw", time: "11:33", creator: "那個女生 Kiki" },
    ],
  },

  {
    id: "chengfu-seafood",
    name: "澄福鮮酥雞（海線）",
    city: "高雄",
    category: "lunch",
    area: "茄萣區",
    address: "高雄市茄萣區頂漁路 19 號",
    days: [2],
    price: "NT$150-400/人",
    must_try: ["炸海鮮拼盤", "炸蚵"],
    note: "⚠️ 高雄海線（茄萣區），距萬豪 ~40 分鐘車程。海線半日遊替代行程。",
    youtube: [
      { id: "fou8Sk3VPRw", creator: "厭世甜點店" },
    ],
  },

  {
    id: "yongji-meatball",
    name: "永吉肉圓（海線）",
    city: "高雄",
    category: "snack",
    area: "茄萣區",
    address: "高雄市茄萣區仁愛路二段 48 號",
    days: [2],
    price: "NT$40-100/人",
    must_try: ["肉圓", "四神湯"],
    note: "⚠️ 海線茄萣區。海線半日遊候選。",
    youtube: [
      { id: "fou8Sk3VPRw", creator: "厭世甜點店" },
    ],
  },

  {
    id: "dexingtang-herb",
    name: "德興堂中藥房（十全雞燉湯，海線）",
    city: "高雄",
    category: "lunch",
    area: "茄萣區",
    address: "高雄市茄萣區崎漏路 86 號",
    days: [2],
    price: "NT$300-500/人",
    must_try: ["十全雞燉湯", "藥膳料理"],
    note: "⚠️ 海線茄萣區。百年藥行私房菜，需預約。",
    youtube: [
      { id: "fou8Sk3VPRw", creator: "厭世甜點店" },
    ],
  },

  {
    id: "baoning-fish-soup",
    name: "保寧魚湯（海線）",
    city: "高雄",
    category: "breakfast",
    area: "永安區",
    address: "高雄市永安區保安路 203 號",
    days: [2],
    price: "NT$80-150/人",
    must_try: ["虱目魚湯", "滷肉飯"],
    note: "⚠️ 海線永安區。海線半日遊候選。",
    youtube: [
      { id: "fou8Sk3VPRw", creator: "厭世甜點店" },
    ],
  },

  {
    id: "qiuzhiwei-seafood",
    name: "邱之味海鮮店（海線）",
    city: "高雄",
    category: "dinner",
    area: "永安區",
    address: "高雄市永安區永達路 73-3 號",
    days: [2],
    price: "NT$500-1200/人",
    must_try: ["現撈海產", "烏魚子"],
    note: "⚠️ 海線永安區。新鮮海產。",
    youtube: [
      { id: "fou8Sk3VPRw", creator: "厭世甜點店" },
    ],
  },

  {
    id: "yongan-noodle-tudi",
    name: "永安泡麵土地（海線）",
    city: "高雄",
    category: "snack",
    area: "永安區",
    address: "高雄市永安區興達路 67-5 號",
    days: [2],
    price: "NT$50-150/人",
    must_try: ["海景泡麵", "打卡拍照"],
    note: "⚠️ 海線永安區。百萬海景＋泡麵土地公打卡點。",
    youtube: [
      { id: "fou8Sk3VPRw", creator: "厭世甜點店" },
    ],
  },

  {
    id: "laolei-noodle",
    name: "老雷麵店（海線）",
    city: "高雄",
    category: "lunch",
    area: "彌陀區",
    address: "高雄市彌陀區中正路 277 號",
    days: [2],
    price: "NT$60-120/人",
    must_try: ["乾麵", "餛飩湯"],
    note: "⚠️ 海線彌陀區。",
    youtube: [
      { id: "fou8Sk3VPRw", creator: "厭世甜點店" },
    ],
  },

  {
    id: "yuxiang-cafe",
    name: "餘香咖啡（魚塭秘境，海線）",
    city: "高雄",
    category: "cafe",
    area: "彌陀區",
    address: "高雄市彌陀區南寮路光明巷 31-1 號",
    days: [2],
    price: "NT$200-400/人",
    must_try: ["虱目魚沙拉", "咖啡果皮氣泡飲"],
    note: "⚠️ 海線彌陀區。藏身魚塭的秘境咖啡。",
    youtube: [
      { id: "fou8Sk3VPRw", creator: "厭世甜點店" },
    ],
  },

  {
    id: "caiji-oyster",
    name: "蔡記蚵仔寮現撈現炸（海線）",
    city: "高雄",
    category: "lunch",
    area: "梓官區",
    address: "高雄市梓官區港九街 84 號",
    days: [2],
    price: "NT$200-500/人",
    must_try: ["現撈炸海鮮", "炸蚵"],
    note: "⚠️ 海線梓官區。蚵仔寮漁市媲美餐廳等級。",
    youtube: [
      { id: "fou8Sk3VPRw", creator: "厭世甜點店" },
    ],
  },

  {
    id: "keliao-dumpling",
    name: "蚵寮水餃王（海線）",
    city: "高雄",
    category: "lunch",
    area: "梓官區",
    address: "高雄市梓官區禮仁路 80 號",
    days: [2],
    price: "NT$60-150/人",
    must_try: ["蚵仔水餃", "韭菜水餃"],
    note: "⚠️ 海線梓官區。蚵仔寮水餃王。",
    youtube: [
      { id: "fou8Sk3VPRw", creator: "厭世甜點店" },
    ],
  },

  // === 沿途服務區 · Day 1 南下 & Day 3 北上 ===
  {
    id: "xihu-rest-stop",
    name: "西湖服務區（里山森林魔法村）",
    city: "苗栗",
    category: "roadside",
    area: "國道3號 135K 南下",
    address: "苗栗縣西湖鄉 國道3號 135K+300",
    days: [1, 3],
    price: "NT$50-200/人",
    must_try: ["傳說龍鬚糖", "飛牛牧場烤布丁", "舞藝橙全自動手沖咖啡"],
    note: "2024 改裝「里山森林魔法村」主題，全國道唯一智能手沖咖啡機。台北出發 1.5–2h 抵達，第一站最佳。",
  },
  {
    id: "xiluo-rest-stop",
    name: "西螺服務區（南站）",
    city: "雲林",
    category: "roadside",
    area: "國道1號 230K 南下",
    address: "雲林縣西螺鎮 國道1號 230K",
    days: [1, 3],
    price: "NT$80-250/人",
    must_try: ["東港漁鄉蛋包旗魚燒", "西螺麻糬大王", "西螺醬油伴手禮"],
    note: "以雲林農特產為主題。有時間可下交流道到延平老街（車程 10 分）吃琴連碗粿豆皮肉羹湯。",
  },
  {
    id: "xiluo-old-street",
    name: "琴連碗粿城（西螺延平老街）",
    city: "雲林",
    category: "roadside",
    area: "西螺交流道下",
    address: "雲林縣西螺鎮延平路（延平老街）",
    days: [1, 3],
    price: "NT$100-250/人",
    must_try: ["豆皮肉羹湯", "三角大水餃", "西螺麻糬", "良星堂豆花"],
    note: "不趕時間強烈推薦跳過服務區改下交流道。西螺醬油丸莊觀光工廠可參觀。",
  },
  {
    id: "taian-rest-stop",
    name: "泰安服務區（南站）",
    city: "台中",
    category: "roadside",
    area: "國道1號 171K 南下",
    address: "台中市后里區 國道1號 171K",
    days: [1, 3],
    price: "NT$100-250/人",
    must_try: ["積木星巴克打卡", "鬍鬚張魯肉飯", "純白旋轉木馬"],
    note: "積木城堡造型星巴克＋旋轉木馬網美點。若走國1，從台北約 2h 可達。",
  },
  {
    id: "dongshan-rest-stop",
    name: "東山服務區（南霸天）",
    city: "台南",
    category: "roadside",
    area: "國道3號 319K 南下",
    address: "台南市東山區 國道3號 319K+820",
    days: [1, 3],
    price: "NT$80-300/人",
    must_try: ["東山鴨頭（滷後炸）", "周氏蝦捲", "所長茶葉蛋", "銀波布丁"],
    note: "全台最大服務區，機場航廈造型＋水漾魚海底隧道。最道地東山鴨頭需下交流道到東山老街。進高雄前最後大站。",
  },
];

const TRANSPORT = {
  sections: [
    {
      icon: "🚗",
      title: "台北 ↔ 高雄（自駕）",
      type: "table",
      items: [
        { route: "國道3號（北二高／福高）", path: "台北 → 高雄", time: "4h30m～5h", fare: "ETC 約 NT$420",
          note: "推薦去程：車流較少、路線順，接國10進高雄市區" },
        { route: "國道1號（中山高）", path: "台北 → 高雄", time: "4h30m～5h30m", fare: "ETC 約 NT$430",
          note: "回程選項：經台中都會區較擠；但接高雄市區較直接" },
      ],
      note: "週五早上南下、週日 11:00 前北返最順；避開週日 15:00–21:00 國道塞車尖峰。總油＋過路費單程粗估 NT$1,500–2,000。",
    },
    {
      icon: "🛣️",
      title: "建議休息站",
      type: "options",
      items: [
        { name: "西湖服務區（國3，苗栗）", time: "出發後 ~1.5h", fare: "—",
          note: "南下第一個大站，早餐／智能手沖咖啡／伴手禮" },
        { name: "西螺服務區（國1，雲林）", time: "出發後 ~3h", fare: "—",
          note: "腹地大、雲林農特產；跳服務區改下交流道到延平老街更有料" },
        { name: "東山服務區（國3，台南）", time: "出發後 ~3.5h", fare: "—",
          note: "進高雄前最後大站，東山鴨頭必買；占地最大" },
      ],
      note: "單趟建議中途休息 1–2 次，每次 15–20 分，避免疲勞駕駛。",
    },
    {
      icon: "🎤",
      title: "高雄萬豪 ↔ 高雄巨蛋（4/24 演唱會）",
      type: "table",
      items: [
        { route: "Uber ／ 計程車", path: "萬豪 → 巨蛋", time: "~15 分", fare: "NT$180–250",
          note: "最快、最省力。散場建議提前在 App 叫車（加成時段）" },
        { route: "自駕", path: "萬豪 → 巨蛋", time: "~15 分", fare: "停車 NT$30/h",
          note: "巨蛋旁有大型停車場（漢神巨蛋、巨蛋商圈）；散場車多慢" },
        { route: "大眾運輸", path: "輕軌 → 紅線 R14", time: "~40 分", fare: "NT$50",
          note: "鼓山區公所 → 哈瑪星 → 高雄車站(R11) 轉紅線 → R14 巨蛋。散場人潮大" },
      ],
      note: "巨蛋地址：高雄市左營區博愛二路 757 號。19:30 開場，建議 18:30 前入場；演唱會者 18:00 從飯店出發最穩。",
    },
    {
      icon: "🅿️",
      title: "飯店停車",
      type: "info-rows",
      items: [
        { key: "高雄萬豪", val: "附設地下停車場，房客優惠價；Valet 服務可用" },
        { key: "市區景點", val: "駁二／愛河附近有公有停車場（時數計費）" },
        { key: "備援 App", val: "USPACE、iParking 可查即時車位" },
      ],
      note: "入住期間車停飯店，市區移動輕軌／捷運／Uber 更輕鬆。",
    },
    {
      icon: "🚇",
      title: "高雄市區交通（備用）",
      type: "options",
      items: [
        { name: "輕軌（環狀）", time: "每 10–15 分一班", fare: "NT$30",
          note: "飯店步行 5 分到「鼓山區公所」站；可到駁二、大港橋、哈瑪星" },
        { name: "捷運紅線／橘線", time: "每 6–8 分一班", fare: "NT$20–60",
          note: "紅線連左營、巨蛋、美麗島（六合夜市）；橘線連鹽埕埔" },
      ],
      note: "建議備一張一卡通，搭車 8 折。",
    },
  ],
};

const TIPS = {
  sections: [
    {
      icon: "☀️",
      title: "四月底高雄天氣",
      type: "info-rows",
      items: [
        { key: "氣溫", val: "22–29°C" },
        { key: "體感", val: "舒服，偶有午後悶熱" },
        { key: "降雨", val: "乾季尾聲，雨機率低" },
        { key: "UV 指數", val: "8–9（強），需防曬" },
      ],
      note: "建議穿短袖＋薄外套（飯店／演唱會冷氣強），帶墨鏡、防曬乳。",
    },
    {
      icon: "🎒",
      title: "打包提醒（4 人同行）",
      type: "checklist",
      items: [
        "身分證 × 4（飯店 check-in、每人一張）",
        "駕照＋行照（自駕必備，建議兩人輪流開）",
        "ETC 卡／確認餘額足夠（單趟過路費約 NT$420）",
        "信用卡＋少量現金（夜市、老店、停車場）",
        "一卡通或悠遊卡 × 4（搭輕軌／捷運備用）",
        "換洗衣物（三天兩夜，含演唱會穿搭）",
        "防曬乳＋墨鏡＋帽子",
        "萬豪常客號（升等／早餐優先）",
      ],
    },
    {
      icon: "🎤",
      title: "演唱會提醒（4/24 19:30 高雄巨蛋）",
      type: "checklist",
      items: [
        "紙本／電子票券備妥，身分證備查",
        "行動電源（手機入場／散場叫車）",
        "耳塞（整晚聲壓高，保護聽力）",
        "應援毛巾、燈棒、手燈（依演出者規定）",
        "防寒薄外套（館內冷氣）",
        "18:00 從飯店出發，18:30 前到場較穩",
        "散場 App 預先叫車，避開排班車人龍",
      ],
    },
    {
      icon: "🚗",
      title: "自駕提醒",
      type: "checklist",
      items: [
        "出發前檢查：胎壓、機油、雨刷水、備胎",
        "油箱加滿再上國道（國道加油站較貴）",
        "Google Maps 下載高雄離線地圖",
        "4 人可兩位輪流開車，每 2h 換手或停服務區",
        "ETC 餘額 < NT$500 先儲值（遠通電收 App）",
        "Day 3 北返建議 11:00 前出發，避週日 15:00–21:00 塞車尖峰",
      ],
    },
  ],
};

const SIGHTS = [
  {
    name: "駁二藝術特區",
    city: "高雄",
    day: 2,
    time: "下午",
    note: "鹽埕區舊倉庫改造，展覽＋文創＋輕軌站旁，適合下午散步。",
    address: "高雄市鹽埕區大勇路 1 號",
  },
  {
    name: "愛河灣",
    city: "高雄",
    day: 1,
    time: "傍晚",
    note: "日落後點燈特別美，飯店步行可達。",
    address: "高雄市鼓山區愛河灣",
  },
  {
    name: "大港橋",
    city: "高雄",
    day: 1,
    time: "傍晚",
    note: "亞洲首座水平旋轉橋，每日 15:00 旋轉開合；棧貳庫吃海鮮順看。",
    address: "高雄市鹽埕區蓬萊路 17 號",
  },
  {
    name: "棧貳庫 KW2",
    city: "高雄",
    day: 1,
    time: "晚上",
    note: "老倉庫改造，海景餐廳＋小店；Day 1 三人夜遊首選。",
    address: "高雄市鼓山區蓬萊路 17 號",
  },
  {
    name: "高雄巨蛋",
    city: "高雄",
    day: 1,
    time: "晚上 19:30",
    note: "4/24 演唱會場地；旁有漢神巨蛋商圈可順逛。",
    address: "高雄市左營區博愛二路 757 號",
  },
  {
    name: "西子灣／打狗英國領事館",
    city: "高雄",
    day: 2,
    time: "下午",
    note: "夕陽＋山海一線最美；從哈瑪星騎 YouBike 或走路 15 分可達。",
    address: "高雄市鼓山區蓮海路 20 號",
  },
  {
    name: "哈瑪星代天宮老街",
    city: "高雄",
    day: 2,
    time: "中午",
    note: "廟口老店群，汕頭麵、黑輪、古早味一次滿足。",
    address: "高雄市鼓山區鼓波街 27 號",
  },
  {
    name: "壽山動物園",
    city: "高雄",
    day: 2,
    time: "上午",
    note: "2022 改造後全新開幕，天空步道看動物無圍欄。離飯店 15 分車程，門票佛心（全票 NT$40）。週一公休。",
    address: "高雄市鼓山區萬壽路 350 號",
  },
  {
    name: "蓮池潭龍虎塔",
    city: "高雄",
    day: 2,
    time: "夜晚",
    note: "CNN 評選高雄必遊 No.1；龍虎塔 2024 年整修重開，進龍出虎才吉利。免費、夜景最美。",
    address: "高雄市左營區蓮潭路",
  },
  {
    name: "佛光山佛陀紀念館",
    city: "高雄",
    day: 3,
    time: "上午",
    note: "全台最大佛教道場，108 米大佛＋八塔一宇，鎮館之寶佛牙舍利。免費入園，停車免費，Day 3 北返順遊。",
    address: "高雄市大樹區統嶺里統嶺路 1 號",
  },
  {
    name: "旗津半島（搭渡輪）",
    city: "高雄",
    day: 2,
    time: "下午",
    note: "鼓山渡船站搭 5 分鐘渡輪到旗津（NT$30），海上看高雄港景。旗津老街海鮮、彩虹教堂、風車公園、燈塔一條線。車停鼓山渡船站旁停車場，人過去玩比較輕鬆。",
    address: "高雄市鼓山區濱海一路 109 號（鼓山渡船站）",
  },
  {
    name: "衛武營國家藝術文化中心",
    city: "高雄",
    day: 2,
    time: "下午",
    note: "全球最大單一屋頂表演藝術中心，建築外型像巨大珊瑚。免費入內參觀公共空間，對面「衛武迷迷村」是彩繪社區打卡熱點。演出需另購票（opentix.life）。",
    address: "高雄市鳳山區三多一路 1 號",
  },
  {
    name: "美濃客家文物館 ／ 旗山老街",
    city: "高雄",
    day: 3,
    time: "下午（替代行程）",
    note: "自駕族才划算的半日遊（無大眾運輸）：美濃粄條＋客家文物館＋油紙傘彩繪 → 旗山老街巴洛克建築＋香蕉蛋糕。佛光山下來順路。若 Day 3 不趕回程可取代大樹麵匠。",
    address: "高雄市美濃區民族路 49-3 號（客家文物館）",
  },
];

window.TRIP_DATA = { TRIP, DAYS, CATEGORIES, RESTAURANTS, TRANSPORT, TIPS, SIGHTS };
